/**
 * Reversa Question Database (Theme Based)
 * 初級：3文字
 * 中級：4〜6文字
 * 上級：7〜10文字
 */
const QUESTION_DATABASE = {
    beginner: [
        {"word": "きつね", "ruby": ["き", "つ", "ね",
        {"word": "いちご", "ruby": ["い", "ち", "ご"], "reverse": "ごちい", "bg": "bg_beginner_1.png"},
        {"word": "すいか", "ruby": ["す", "い", "か"], "reverse": "かいす", "bg": "bg_beginner_1.png"},
        {"word": "ばなな", "ruby": ["ば", "な", "な"], "reverse": "ななば", "bg": "bg_beginner_1.png"},
        {"word": "めろん", "ruby": ["め", "ろ", "ん"], "reverse": "んろめ", "bg": "bg_beginner_1.png"},
        {"word": "ぶどう", "ruby": ["ぶ", "ど", "う"], "reverse": "うどぶ", "bg": "bg_beginner_1.png"},
        {"word": "れたす", "ruby": ["れ", "た", "す"], "reverse": "すたれ", "bg": "bg_beginner_1.png"},
        {"word": "とまと", "ruby": ["と", "ま", "と"], "reverse": "とまと", "bg": "bg_beginner_1.png"},
        {"word": "なすび", "ruby": ["な", "す", "び"], "reverse": "びすな", "bg": "bg_beginner_1.png"},
        {"word": "きのこ", "ruby": ["き", "の", "こ"], "reverse": "このき", "bg": "bg_beginner_1.png"},
        {"word": "たけのこ", "ruby": ["た", "け", "の", "こ"], "reverse": "このけた", "bg": "bg_beginner_1.png"},
        {"word": "つくえ", "ruby": ["つ", "く", "え"], "reverse": "えくつ", "bg": "bg_beginner_1.png"},
        {"word": "いすだ", "ruby": ["い", "す", "だ"], "reverse": "だすい", "bg": "bg_beginner_1.png"},
        {"word": "かばん", "ruby": ["か", "ば", "ん"], "reverse": "んばか", "bg": "bg_beginner_1.png"},
        {"word": "さいふ", "ruby": ["さ", "い", "ふ"], "reverse": "ふいさ", "bg": "bg_beginner_1.png"},
        {"word": "はさみ", "ruby": ["は", "さ", "み"], "reverse": "みさは", "bg": "bg_beginner_1.png"},
        {"word": "めがね", "ruby": ["め", "が", "ね"], "reverse": "ねがめ", "bg": "bg_beginner_1.png"},
        {"word": "とけい", "ruby": ["と", "け", "い"], "reverse": "いけと", "bg": "bg_beginner_1.png"},
        {"word": "てれび", "ruby": ["て", "れ", "び"], "reverse": "びれて", "bg": "bg_beginner_1.png"},
        {"word": "らじお", "ruby": ["ら", "じ", "お"], "reverse": "おじら", "bg": "bg_beginner_1.png"},
        {"word": "くるま", "ruby": ["く", "る", "ま"], "reverse": "まるく", "bg": "bg_beginner_1.png"},
        {"word": "ばいく", "ruby": ["ば", "い", "く"], "reverse": "くいば", "bg": "bg_beginner_1.png"},
        {"word": "ふねだ", "ruby": ["ふ", "ね", "だ"], "reverse": "だねふ", "bg": "bg_beginner_1.png"},
        {"word": "そらだ", "ruby": ["そ", "ら", "だ"], "reverse": "だらそ", "bg": "bg_beginner_1.png"},
        {"word": "うみだ", "ruby": ["う", "み", "だ"], "reverse": "だみう", "bg": "bg_beginner_1.png"},
        {"word": "やまだ", "ruby": ["や", "ま", "だ"], "reverse": "だまや", "bg": "bg_beginner_1.png"},
        {"word": "かわだ", "ruby": ["か", "わ", "だ"], "reverse": "だわか", "bg": "bg_beginner_1.png"},
        {"word": "はなだ", "ruby": ["は", "な", "だ"], "reverse": "だなは", "bg": "bg_beginner_1.png"},
        {"word": "もりだ", "ruby": ["も", "り", "だ"], "reverse": "だりも", "bg": "bg_beginner_1.png"},
        {"word": "こめだ", "ruby": ["こ", "め", "だ"], "reverse": "だめこ", "bg": "bg_beginner_1.png"},
        {"word": "かめだ", "ruby": ["か", "め", "だ"], "reverse": "だめか", "bg": "bg_beginner_1.png"}], "reverse": "ねつき", "bg": "bg_beginner_3.png"},
        {"word": "さくら", "ruby": ["さ", "く", "ら"], "reverse": "らくさ", "bg": "bg_beginner_1.png"},
        {"word": "りんご", "ruby": ["り", "ん", "ご"], "reverse": "ごんり", "bg": "bg_beginner_3.png"},
        {"word": "みかん", "ruby": ["み", "か", "ん"], "reverse": "んかみ", "bg": "bg_beginner_1.png"},
        {"word": "くるま", "ruby": ["く", "る", "ま"], "reverse": "まるく", "bg": "bg_beginner_2.png"},
        {"word": "めがね", "ruby": ["め", "が", "ね"], "reverse": "ねがめ", "bg": "bg_beginner_3.png"},
        {"word": "からす", "ruby": ["か", "ら", "す"], "reverse": "すらか", "bg": "bg_beginner_1.png"},
        {"word": "すずめ", "ruby": ["す", "ず", "め"], "reverse": "めずす", "bg": "bg_beginner_2.png"},
        {"word": "うさぎ", "ruby": ["う", "さ", "ぎ"], "reverse": "ぎさう", "bg": "bg_beginner_3.png"},
        {"word": "くじら", "ruby": ["く", "じ", "ら"], "reverse": "らじく", "bg": "bg_beginner_2.png"},
        {"word": "ひよこ", "ruby": ["ひ", "よ", "こ"], "reverse": "こよひ", "bg": "bg_beginner_1.png"},
        {"word": "かえる", "ruby": ["か", "え", "る"], "reverse": "るえか", "bg": "bg_beginner_2.png"},
        {"word": "めだか", "ruby": ["め", "だ", "か"], "reverse": "かだめ", "bg": "bg_beginner_3.png"},
        {"word": "さかな", "ruby": ["さ", "か", "な"], "reverse": "なかさ", "bg": "bg_beginner_1.png"},
        {"word": "ごはん", "ruby": ["ご", "は", "ん"], "reverse": "んはご", "bg": "bg_beginner_2.png"},
        {"word": "たまご", "ruby": ["た", "ま", "ご"], "reverse": "ごまた", "bg": "bg_beginner_1.png"},
        {"word": "うどん", "ruby": ["う", "ど", "ん"], "reverse": "んどう", "bg": "bg_beginner_2.png"},
        {"word": "ぽてと", "ruby": ["ぽ", "て", "と"], "reverse": "とてぽ", "bg": "bg_beginner_1.png"},
        {"word": "つくえ", "ruby": ["つ", "く", "え"], "reverse": "えくつ", "bg": "bg_beginner_2.png"},
        {"word": "かばん", "ruby": ["か", "ば", "ん"], "reverse": "んばか", "bg": "bg_beginner_3.png"},
        {"word": "さいふ", "ruby": ["さ", "い", "ふ"], "reverse": "ふいさ", "bg": "bg_beginner_3.png"},
    ],
    intermediate: [
        {"word": "かたつむり", "ruby": ["か", "た", "つ", "む", "り",
        {"word": "ひまわり", "ruby": ["ひ", "ま", "わ", "り"], "reverse": "りわまひ", "bg": "bg_beginner_2.png"},
        {"word": "たんぽぽ", "ruby": ["た", "ん", "ぽ", "ぽ"], "reverse": "ぽぽんた", "bg": "bg_beginner_2.png"},
        {"word": "あさがお", "ruby": ["あ", "さ", "が", "お"], "reverse": "おがさあ", "bg": "bg_beginner_2.png"},
        {"word": "おにぎり", "ruby": ["お", "に", "ぎ", "り"], "reverse": "りぎにお", "bg": "bg_beginner_2.png"},
        {"word": "おべんとう", "ruby": ["お", "べ", "ん", "と", "う"], "reverse": "うとんべお", "bg": "bg_beginner_2.png"},
        {"word": "せんたくき", "ruby": ["せ", "ん", "た", "く", "き"], "reverse": "きくたんせ", "bg": "bg_beginner_2.png"},
        {"word": "れいぞうこ", "ruby": ["れ", "い", "ぞ", "う", "こ"], "reverse": "こうぞいれ", "bg": "bg_beginner_2.png"},
        {"word": "どうぶつえん", "ruby": ["ど", "う", "ぶ", "つ", "え", "ん"], "reverse": "んえつぶうど", "bg": "bg_beginner_2.png"},
        {"word": "しんかんせん", "ruby": ["し", "ん", "か", "ん", "せ", "ん"], "reverse": "んせんかんし", "bg": "bg_beginner_2.png"},
        {"word": "ひこうき", "ruby": ["ひ", "こ", "う", "き"], "reverse": "きうこひ", "bg": "bg_beginner_2.png"},
        {"word": "じどうしゃ", "ruby": ["じ", "ど", "う", "しゃ"], "reverse": "しゃうどじ", "bg": "bg_beginner_2.png"},
        {"word": "おーとばい", "ruby": ["お", "ー", "と", "ば", "い"], "reverse": "いばとーお", "bg": "bg_beginner_2.png"},
        {"word": "としょかん", "ruby": ["と", "しょ", "か", "ん"], "reverse": "んかしょと", "bg": "bg_beginner_2.png"},
        {"word": "びょういん", "ruby": ["びょ", "う", "い", "ん"], "reverse": "んいうびょ", "bg": "bg_beginner_2.png"},
        {"word": "がっこう", "ruby": ["が", "っ", "こ", "う"], "reverse": "うこっが", "bg": "bg_beginner_2.png"},
        {"word": "こうえん", "ruby": ["こ", "う", "え", "ん"], "reverse": "んえうこ", "bg": "bg_beginner_2.png"},
        {"word": "すべりだい", "ruby": ["す", "べ", "り", "だ", "い"], "reverse": "いだりべす", "bg": "bg_beginner_2.png"},
        {"word": "ぶらんこ", "ruby": ["ぶ", "ら", "ん", "こ"], "reverse": "こんらぶ", "bg": "bg_beginner_2.png"},
        {"word": "すいぞくかん", "ruby": ["す", "い", "ぞ", "く", "か", "ん"], "reverse": "んかくぞいす", "bg": "bg_beginner_2.png"},
        {"word": "はくぶつかん", "ruby": ["は", "く", "ぶ", "つ", "か", "ん"], "reverse": "んかつぶくは", "bg": "bg_beginner_2.png"},
        {"word": "びじゅつかん", "ruby": ["び", "じゅ", "つ", "か", "ん"], "reverse": "んかつじゅび", "bg": "bg_beginner_2.png"},
        {"word": "たいよう", "ruby": ["た", "い", "よ", "う"], "reverse": "うよいた", "bg": "bg_beginner_2.png"},
        {"word": "おつきさま", "ruby": ["お", "つ", "き", "さ", "ま"], "reverse": "まさきつお", "bg": "bg_beginner_2.png"},
        {"word": "おほしさま", "ruby": ["お", "ほ", "し", "さ", "ま"], "reverse": "まさしほお", "bg": "bg_beginner_2.png"},
        {"word": "あまのがわ", "ruby": ["あ", "ま", "の", "が", "わ"], "reverse": "わがのまあ", "bg": "bg_beginner_2.png"},
        {"word": "なつやすみ", "ruby": ["な", "つ", "や", "す", "み"], "reverse": "みすやつな", "bg": "bg_beginner_2.png"},
        {"word": "ふゆやすみ", "ruby": ["ふ", "ゆ", "や", "す", "み"], "reverse": "みすやゆふ", "bg": "bg_beginner_2.png"},
        {"word": "あめふり", "ruby": ["あ", "め", "ふ", "り"], "reverse": "りふめあ", "bg": "bg_beginner_2.png"},
        {"word": "ゆきだるま", "ruby": ["ゆ", "き", "だ", "る", "ま"], "reverse": "まるだきゆ", "bg": "bg_beginner_2.png"},
        {"word": "かみなり", "ruby": ["か", "み", "な", "り"], "reverse": "りなみか", "bg": "bg_beginner_2.png"}], "reverse": "りむつたか", "bg": "bg_beginner_1.png"},
        {"word": "ほととぎす", "ruby": ["ほ", "と", "と", "ぎ", "す"], "reverse": "すぎととほ", "bg": "bg_beginner_2.png"},
        {"word": "おぼろづき", "ruby": ["お", "ぼ", "ろ", "づ", "き"], "reverse": "きづろぼお", "bg": "bg_beginner_3.png"},
        {"word": "あきあかね", "ruby": ["あ", "き", "あ", "か", "ね"], "reverse": "ねかあきあ", "bg": "bg_beginner_1.png"},
        {"word": "しもばしら", "ruby": ["し", "も", "ば", "し", "ら"], "reverse": "らしばもし", "bg": "bg_beginner_2.png"},
        {"word": "こいのぼり", "ruby": ["こ", "い", "の", "ぼ", "り"], "reverse": "りぼのいこ", "bg": "bg_beginner_3.png"},
        {"word": "おとしだま", "ruby": ["お", "と", "し", "だ", "ま"], "reverse": "まだしとお", "bg": "bg_beginner_1.png"},
        {"word": "ひなまつり", "ruby": ["ひ", "な", "ま", "つ", "り"], "reverse": "りつまなひ", "bg": "bg_beginner_2.png"},
        {"word": "わらびもち", "ruby": ["わ", "ら", "び", "も", "ち"], "reverse": "ちもびらわ", "bg": "bg_beginner_3.png"},
        {"word": "かしわもち", "ruby": ["か", "し", "わ", "も", "ち"], "reverse": "ちもわしか", "bg": "bg_beginner_1.png"},
        {"word": "だいふくもち", "ruby": ["だ", "い", "ふ", "く", "も", "ち"], "reverse": "ちもくふいだ", "bg": "bg_beginner_2.png"},
        {"word": "ふゆげしき", "ruby": ["ふ", "ゆ", "げ", "し", "き"], "reverse": "きしげゆふ", "bg": "bg_beginner_3.png"},
        {"word": "つきみだんご", "ruby": ["つ", "き", "み", "だ", "ん", "ご"], "reverse": "ごんだみきつ", "bg": "bg_beginner_1.png"},
        {"word": "あまのがわ", "ruby": ["あ", "ま", "の", "が", "わ"], "reverse": "わがのまあ", "bg": "bg_beginner_2.png"},
        {"word": "あかいふね", "ruby": ["あ", "か", "い", "ふ", "ね"], "reverse": "ねふいかあ", "bg": "bg_beginner_3.png"},
        {"word": "あきのそら", "ruby": ["あ", "き", "の", "そ", "ら"], "reverse": "らそのきあ", "bg": "bg_beginner_1.png"},
        {"word": "はるのやま", "ruby": ["は", "る", "の", "や", "ま"], "reverse": "まやのるは", "bg": "bg_beginner_2.png"},
        {"word": "なつのみず", "ruby": ["な", "つ", "の", "み", "ず"], "reverse": "ずみのつな", "bg": "bg_beginner_3.png"},
        {"word": "ふゆのゆき", "ruby": ["ふ", "ゆ", "の", "ゆ", "き"], "reverse": "きゆのゆふ", "bg": "bg_beginner_1.png"},
        {"word": "つきのひかり", "ruby": ["つ", "き", "の", "ひ", "か", "り"], "reverse": "りかひのきつ", "bg": "bg_beginner_2.png"},
        {"word": "ほしのよる", "ruby": ["ほ", "し", "の", "よ", "る"], "reverse": "るよのしほ", "bg": "bg_beginner_3.png"},
        {"word": "あおいとり", "ruby": ["あ", "お", "い", "と", "り"], "reverse": "りといおあ", "bg": "bg_beginner_1.png"},
        {"word": "しろいくも", "ruby": ["し", "ろ", "い", "く", "も"], "reverse": "もくいろし", "bg": "bg_beginner_2.png"},
        {"word": "やまのみち", "ruby": ["や", "ま", "の", "み", "ち"], "reverse": "ちみのまや", "bg": "bg_beginner_3.png"},
        {"word": "うみのなみ", "ruby": ["う", "み", "の", "な", "み"], "reverse": "みなのみう", "bg": "bg_beginner_1.png"},
        {"word": "ひかるかぜ", "ruby": ["ひ", "か", "る", "か", "ぜ"], "reverse": "ぜかるかひ", "bg": "bg_beginner_2.png"},
        {"word": "きいろいはな", "ruby": ["き", "い", "ろ", "い", "は", "な"], "reverse": "なはいろいき", "bg": "bg_beginner_3.png"},
        {"word": "あかいりんご", "ruby": ["あ", "か", "い", "り", "ん", "ご"], "reverse": "ごんりいかあ", "bg": "bg_beginner_1.png"},
        {"word": "あまいみかん", "ruby": ["あ", "ま", "い", "み", "か", "ん"], "reverse": "んかみいまあ", "bg": "bg_beginner_2.png"},
        {"word": "まるいすいか", "ruby": ["ま", "る", "い", "す", "い", "か"], "reverse": "かいすいるま", "bg": "bg_beginner_3.png"},
        {"word": "ながいはし", "ruby": ["な", "が", "い", "は", "し"], "reverse": "しはいがな", "bg": "bg_beginner_1.png"},
        {"word": "まるいつくえ", "ruby": ["ま", "る", "い", "つ", "く", "え"], "reverse": "えくついるま", "bg": "bg_beginner_2.png"},
        {"word": "ひろいにわ", "ruby": ["ひ", "ろ", "い", "に", "わ"], "reverse": "わにいろひ", "bg": "bg_beginner_3.png"},
        {"word": "ふるいまち", "ruby": ["ふ", "る", "い", "ま", "ち"], "reverse": "ちまいるふ", "bg": "bg_beginner_1.png"},
        {"word": "たのしいうた", "ruby": ["た", "の", "し", "い", "う", "た"], "reverse": "たういしのた", "bg": "bg_beginner_2.png"},
        {"word": "きれいなえ", "ruby": ["き", "れ", "い", "な", "え"], "reverse": "えないれき", "bg": "bg_beginner_3.png"},
        {"word": "はやいくるま", "ruby": ["は", "や", "い", "く", "る", "ま"], "reverse": "まるくいやは", "bg": "bg_beginner_1.png"},
        {"word": "おもいかばん", "ruby": ["お", "も", "い", "か", "ば", "ん"], "reverse": "んばかいもお", "bg": "bg_beginner_2.png"},
        {"word": "ひろいうみ", "ruby": ["ひ", "ろ", "い", "う", "み"], "reverse": "みういろひ", "bg": "bg_beginner_3.png"},
        {"word": "あおいくるま", "ruby": ["あ", "お", "い", "く", "る", "ま"], "reverse": "まるくいおあ", "bg": "bg_beginner_1.png"},
        {"word": "やまびこのこえ", "ruby": ["や", "ま", "び", "こ", "の", "こ", "え"], "reverse": "えこのこびまや", "bg": "bg_beginner_2.png"},
        {"word": "あめあがりのそら", "ruby": ["あ", "め", "あ", "が", "り", "の", "そ", "ら"], "reverse": "らそのりがあめあ", "bg": "bg_beginner_3.png"},
        {"word": "もりのかくれんぼ", "ruby": ["も", "り", "の", "か", "く", "れ", "ん", "ぼ"], "reverse": "ぼんれくかのりも", "bg": "bg_beginner_1.png"},
        {"word": "さくらのつぼみ", "ruby": ["さ", "く", "ら", "の", "つ", "ぼ", "み"], "reverse": "みぼつのらくさ", "bg": "bg_beginner_2.png"},
        {"word": "あきのみかく", "ruby": ["あ", "き", "の", "み", "か", "く"], "reverse": "くかみのきあ", "bg": "bg_beginner_3.png"},
        {"word": "ひかりのわ", "ruby": ["ひ", "か", "り", "の", "わ"], "reverse": "わのりかひ", "bg": "bg_beginner_1.png"},
        {"word": "ふねのたび", "ruby": ["ふ", "ね", "の", "た", "び"], "reverse": "びたのねふ", "bg": "bg_beginner_2.png"},
        {"word": "そらのたび", "ruby": ["そ", "ら", "の", "た", "び"], "reverse": "びたのらそ", "bg": "bg_beginner_3.png"},
        {"word": "ゆめのなか", "ruby": ["ゆ", "め", "の", "な", "か"], "reverse": "かなのめゆ", "bg": "bg_beginner_1.png"},
        {"word": "あさのひかり", "ruby": ["あ", "さ", "の", "ひ", "か", "り"], "reverse": "りかひのさあ", "bg": "bg_beginner_2.png"},
    ],
    advanced: [
        {"word": "あまのがわきらきら", "ruby": ["あ", "ま", "の", "が", "わ", "き", "ら", "き", "ら",
        {"word": "じどうはんばいき", "ruby": ["じ", "ど", "う", "は", "ん", "ば", "い", "き"], "reverse": "きいばんはうどじ", "bg": "bg_beginner_3.png"},
        {"word": "しょうぼうじどうしゃ", "ruby": ["しょ", "う", "ぼ", "う", "じ", "ど", "う", "しゃ"], "reverse": "しゃうどじうぼうしょ", "bg": "bg_beginner_3.png"},
        {"word": "きゅうきゅうしゃがくる", "ruby": ["きゅ", "う", "きゅ", "う", "しゃ", "が", "く", "る"], "reverse": "るくがしゃうきゅうきゅ", "bg": "bg_beginner_3.png"},
        {"word": "しんぶんをよむ", "ruby": ["し", "ん", "ぶ", "ん", "を", "よ", "む"], "reverse": "むよをんぶんし", "bg": "bg_beginner_3.png"},
        {"word": "ごはんをたべる", "ruby": ["ご", "は", "ん", "を", "た", "べ", "る"], "reverse": "るべたをんはご", "bg": "bg_beginner_3.png"},
        {"word": "おふろにはいる", "ruby": ["お", "ふ", "ろ", "に", "は", "い", "る"], "reverse": "るいはにろふお", "bg": "bg_beginner_3.png"},
        {"word": "あしたさんぽにいく", "ruby": ["あ", "し", "た", "さ", "ん", "ぽ", "に", "い", "く"], "reverse": "くいにぽんさたしあ", "bg": "bg_beginner_3.png"},
        {"word": "ほんをたくさんよむ", "ruby": ["ほ", "ん", "を", "た", "く", "さ", "ん", "よ", "む"], "reverse": "むよんさくたをんほ", "bg": "bg_beginner_3.png"},
        {"word": "てにすをしましょう", "ruby": ["て", "に", "す", "を", "し", "ま", "しょ", "う"], "reverse": "うしょましをすにて", "bg": "bg_beginner_3.png"},
        {"word": "やきゅうをみにいく", "ruby": ["や", "きゅ", "う", "を", "み", "に", "い", "く"], "reverse": "くいにみをうきゅや", "bg": "bg_beginner_3.png"},
        {"word": "うみをながめる", "ruby": ["う", "み", "を", "な", "が", "め", "る"], "reverse": "るめがなをみう", "bg": "bg_beginner_3.png"},
        {"word": "たかいやまをのぼる", "ruby": ["た", "か", "い", "や", "ま", "を", "の", "ぼ", "る"], "reverse": "るぼのをまやいかた", "bg": "bg_beginner_3.png"},
        {"word": "おんがくをきく", "ruby": ["お", "ん", "が", "く", "を", "き", "く"], "reverse": "くきをくがんお", "bg": "bg_beginner_3.png"},
        {"word": "ぴあのをたのしくひく", "ruby": ["ぴ", "あ", "の", "を", "た", "の", "し", "く", "ひ", "く"], "reverse": "くひくしのたをのあぴ", "bg": "bg_beginner_3.png"},
        {"word": "ほっかいどうにいく", "ruby": ["ほ", "っ", "か", "い", "ど", "う", "に", "い", "く"], "reverse": "くいにうどいかっほ", "bg": "bg_beginner_3.png"},
        {"word": "せんたくをする", "ruby": ["せ", "ん", "た", "く", "を", "す", "る"], "reverse": "るすをくたんせ", "bg": "bg_beginner_3.png"},
        {"word": "へやのそうじをする", "ruby": ["へ", "や", "の", "そ", "う", "じ", "を", "す", "る"], "reverse": "るすをじうそのやへ", "bg": "bg_beginner_3.png"},
        {"word": "かいものにいく", "ruby": ["か", "い", "も", "の", "に", "い", "く"], "reverse": "くいにのもいか", "bg": "bg_beginner_3.png"},
        {"word": "りょうりをつくる", "ruby": ["りょ", "う", "り", "を", "つ", "く", "る"], "reverse": "るくつをりうりょ", "bg": "bg_beginner_3.png"},
        {"word": "おかあさんにかけ", "ruby": ["お", "か", "あ", "さ", "ん", "に", "か", "け"], "reverse": "けかにんさあかお", "bg": "bg_beginner_3.png"},
        {"word": "でんわをかける", "ruby": ["で", "ん", "わ", "を", "か", "け", "る"], "reverse": "るけかをわんで", "bg": "bg_beginner_3.png"},
        {"word": "てれびをじっとみる", "ruby": ["て", "れ", "び", "を", "じ", "っ", "と", "み", "る"], "reverse": "るみとっじをびれて", "bg": "bg_beginner_3.png"},
        {"word": "ぱそこんをうつ", "ruby": ["ぱ", "そ", "こ", "ん", "を", "う", "つ"], "reverse": "つうをんこそぱ", "bg": "bg_beginner_3.png"},
        {"word": "いっしょうけんめい", "ruby": ["い", "っ", "しょ", "う", "け", "ん", "め", "い"], "reverse": "いめんけうしょっい", "bg": "bg_beginner_3.png"},
        {"word": "まいにちべんきょう", "ruby": ["ま", "い", "に", "ち", "べ", "ん", "きょ", "う"], "reverse": "うきょんべちにいま", "bg": "bg_beginner_3.png"},
        {"word": "しゅくだいをする", "ruby": ["しゅ", "く", "だ", "い", "を", "す", "る"], "reverse": "るすをいだくしゅ", "bg": "bg_beginner_3.png"},
        {"word": "しけんをうける", "ruby": ["し", "け", "ん", "を", "う", "け", "る"], "reverse": "るけうをんけし", "bg": "bg_beginner_3.png"},
        {"word": "うんどうをする", "ruby": ["う", "ん", "ど", "う", "を", "す", "る"], "reverse": "るすをうどんう", "bg": "bg_beginner_3.png"},
        {"word": "あさのさんぽをする", "ruby": ["あ", "さ", "の", "さ", "ん", "ぽ", "を", "す", "る"], "reverse": "るすをぽんさのさあ", "bg": "bg_beginner_3.png"},
        {"word": "こうえんであそぶ", "ruby": ["こ", "う", "え", "ん", "で", "あ", "そ", "ぶ"], "reverse": "ぶそあでんえうこ", "bg": "bg_beginner_3.png"},
        {"word": "おかしをたべる", "ruby": ["お", "か", "し", "を", "た", "べ", "る"], "reverse": "るべたをしかお", "bg": "bg_beginner_3.png"},
        {"word": "おちゃをのむ", "ruby": ["お", "ちゃ", "を", "の", "む"], "reverse": "むのをちゃお", "bg": "bg_beginner_3.png"},
        {"word": "あしたははれだ", "ruby": ["あ", "し", "た", "は", "は", "れ", "だ"], "reverse": "だれははたしあ", "bg": "bg_beginner_3.png"}], "reverse": "らきらきわがのまあ", "bg": "bg_beginner_1.png"},
        {"word": "やまのうえのおてら", "ruby": ["や", "ま", "の", "う", "え", "の", "お", "て", "ら"], "reverse": "らておのえうのまや", "bg": "bg_beginner_2.png"},
        {"word": "あめあがりのにじ", "ruby": ["あ", "め", "あ", "が", "り", "の", "に", "じ"], "reverse": "じにのりがあめあ", "bg": "bg_beginner_3.png"},
        {"word": "もりのおんがくかい", "ruby": ["も", "り", "の", "お", "ん", "が", "く", "か", "い"], "reverse": "いかくがんおのりも", "bg": "bg_beginner_1.png"},
        {"word": "おひさまのひかり", "ruby": ["お", "ひ", "さ", "ま", "の", "ひ", "か", "り"], "reverse": "りかひのまさひお", "bg": "bg_beginner_2.png"},
        {"word": "うみのなかのさかな", "ruby": ["う", "み", "の", "な", "か", "の", "さ", "か", "な"], "reverse": "なかさのかなのみう", "bg": "bg_beginner_3.png"},
        {"word": "そらのうえのほし", "ruby": ["そ", "ら", "の", "う", "え", "の", "ほ", "し"], "reverse": "しほのえうのらそ", "bg": "bg_beginner_1.png"},
        {"word": "ひなまつりのうた", "ruby": ["ひ", "な", "ま", "つ", "り", "の", "う", "た"], "reverse": "たうのりつまなひ", "bg": "bg_beginner_2.png"},
        {"word": "こいのぼりのうた", "ruby": ["こ", "い", "の", "ぼ", "り", "の", "う", "た"], "reverse": "たうのりぼのいこ", "bg": "bg_beginner_3.png"},
        {"word": "あおぞらのしろいくも", "ruby": ["あ", "お", "ぞ", "ら", "の", "し", "ろ", "い", "く", "も"], "reverse": "もくいろしのらぞおあ", "bg": "bg_beginner_1.png"},
        {"word": "あかいはなのなまえ", "ruby": ["あ", "か", "い", "は", "な", "の", "な", "ま", "え"], "reverse": "えまなのなはいかあ", "bg": "bg_beginner_2.png"},
        {"word": "みどりのもりのなか", "ruby": ["み", "ど", "り", "の", "も", "り", "の", "な", "か"], "reverse": "かなのりものりどみ", "bg": "bg_beginner_3.png"},
        {"word": "きいろいくつのあと", "ruby": ["き", "い", "ろ", "い", "く", "つ", "の", "あ", "と"], "reverse": "とあのつくいろいき", "bg": "bg_beginner_1.png"},
        {"word": "くろいくものかげ", "ruby": ["く", "ろ", "い", "く", "も", "の", "か", "げ"], "reverse": "げかのもくいろく", "bg": "bg_beginner_2.png"},
        {"word": "あおいとりのはね", "ruby": ["あ", "お", "い", "と", "り", "の", "は", "ね"], "reverse": "ねはのりといおあ", "bg": "bg_beginner_3.png"},
        {"word": "しろいくまのゆめ", "ruby": ["し", "ろ", "い", "く", "ま", "の", "ゆ", "め"], "reverse": "めゆのまくいろし", "bg": "bg_beginner_1.png"},
        {"word": "はるのかぜのにおい", "ruby": ["は", "る", "の", "か", "ぜ", "の", "に", "お", "い"], "reverse": "いおにのぜかのるは", "bg": "bg_beginner_2.png"},
        {"word": "なつのうみのあおさ", "ruby": ["な", "つ", "の", "う", "み", "の", "あ", "お", "さ"], "reverse": "さおあのみうのつな", "bg": "bg_beginner_3.png"},
        {"word": "あきのやまのいろ", "ruby": ["あ", "き", "の", "や", "ま", "の", "い", "ろ"], "reverse": "ろいのまやのきあ", "bg": "bg_beginner_1.png"},
        {"word": "あしたのゆめのなか", "ruby": ["あ", "し", "た", "の", "ゆ", "め", "の", "な", "か"], "reverse": "かなのめゆのたしあ", "bg": "bg_beginner_2.png"},
        {"word": "きのうのよるのほし", "ruby": ["き", "の", "う", "の", "よ", "る", "の", "ほ", "し"], "reverse": "しほのるよのうのき", "bg": "bg_beginner_3.png"},
        {"word": "おとなのひそひそはなし", "ruby": ["お", "と", "な", "の", "ひ", "そ", "ひ", "そ", "は", "な", "し"], "reverse": "しなはそひそひのなとお", "bg": "bg_beginner_1.png"},
        {"word": "ひみつのたからもの", "ruby": ["ひ", "み", "つ", "の", "た", "か", "ら", "も", "の"], "reverse": "のもらかたのつみひ", "bg": "bg_beginner_2.png"},
        {"word": "ふしぎなまほうのつえ", "ruby": ["ふ", "し", "ぎ", "な", "ま", "ほ", "う", "の", "つ", "え"], "reverse": "えつのうほまなぎしふ", "bg": "bg_beginner_3.png"},
        {"word": "たのしいおまつりのよる", "ruby": ["た", "の", "し", "い", "お", "ま", "つ", "り", "の", "よ", "る"], "reverse": "るよのりつまおいしのた", "bg": "bg_beginner_1.png"},
        {"word": "きれいなみなとのひかり", "ruby": ["き", "れ", "い", "な", "み", "な", "と", "の", "ひ", "か", "り"], "reverse": "りかひのとなみないれき", "bg": "bg_beginner_2.png"},
        {"word": "しずかなもりのなか", "ruby": ["し", "ず", "か", "な", "も", "り", "の", "な", "か"], "reverse": "かなのりもなかずし", "bg": "bg_beginner_3.png"},
        {"word": "あかいりんごをたべる", "ruby": ["あ", "か", "い", "り", "ん", "ご", "を", "た", "べ", "る"], "reverse": "るべたをごんりいかあ", "bg": "bg_beginner_1.png"},
        {"word": "あまいみかんをむく", "ruby": ["あ", "ま", "い", "み", "か", "ん", "を", "む", "く"], "reverse": "くむをんかみいまあ", "bg": "bg_beginner_2.png"},
        {"word": "まるいすいかをきる", "ruby": ["ま", "る", "い", "す", "い", "か", "を", "き", "る"], "reverse": "るきをかいすいるま", "bg": "bg_beginner_3.png"},
        {"word": "あかいふねにのる", "ruby": ["あ", "か", "い", "ふ", "ね", "に", "の", "る"], "reverse": "るのにねふいかあ", "bg": "bg_beginner_1.png"},
        {"word": "あおいくるまをまつ", "ruby": ["あ", "お", "い", "く", "る", "ま", "を", "ま", "つ"], "reverse": "つまをまるくいおあ", "bg": "bg_beginner_2.png"},
        {"word": "きれいなはなをみる", "ruby": ["き", "れ", "い", "な", "は", "な", "を", "み", "る"], "reverse": "るみをなはないれき", "bg": "bg_beginner_3.png"},
        {"word": "たのしいうたをうたう", "ruby": ["た", "の", "し", "い", "う", "た", "を", "う", "た", "う"], "reverse": "うたうをたういしのた", "bg": "bg_beginner_1.png"},
        {"word": "ひろいうみをわたる", "ruby": ["ひ", "ろ", "い", "う", "み", "を", "わ", "た", "る"], "reverse": "るたわをみういろひ", "bg": "bg_beginner_2.png"},
        {"word": "たかいやまにのぼる", "ruby": ["た", "か", "い", "や", "ま", "に", "の", "ぼ", "る"], "reverse": "るぼのにまやいかた", "bg": "bg_beginner_3.png"},
        {"word": "あおいとりをさがす", "ruby": ["あ", "お", "い", "と", "り", "を", "さ", "が", "す"], "reverse": "すがさをりといおあ", "bg": "bg_beginner_1.png"},
        {"word": "ふるいまちをあるく", "ruby": ["ふ", "る", "い", "ま", "ち", "を", "あ", "る", "く"], "reverse": "くるあをちまいるふ", "bg": "bg_beginner_2.png"},
        {"word": "しろいくもをみあげる", "ruby": ["し", "ろ", "い", "く", "も", "を", "み", "あ", "げ", "る"], "reverse": "るげあみをもくいろし", "bg": "bg_beginner_3.png"},
        {"word": "あさのひかりをあびる", "ruby": ["あ", "さ", "の", "ひ", "か", "り", "を", "あ", "び", "る"], "reverse": "るびあをりかひのさあ", "bg": "bg_beginner_1.png"},
        {"word": "ゆめのなかであそぶ", "ruby": ["ゆ", "め", "の", "な", "か", "で", "あ", "そ", "ぶ"], "reverse": "ぶそあでかなのめゆ", "bg": "bg_beginner_2.png"},
        {"word": "ほしのよるをまつ", "ruby": ["ほ", "し", "の", "よ", "る", "を", "ま", "つ"], "reverse": "つまをるよのしほ", "bg": "bg_beginner_3.png"},
        {"word": "はるのひかりのなか", "ruby": ["は", "る", "の", "ひ", "か", "り", "の", "な", "か"], "reverse": "かなのりかひのるは", "bg": "bg_beginner_1.png"},
        {"word": "なつのなみのこえ", "ruby": ["な", "つ", "の", "な", "み", "の", "こ", "え"], "reverse": "えこのみなのつな", "bg": "bg_beginner_2.png"},
        {"word": "あきのむしのこえ", "ruby": ["あ", "き", "の", "む", "し", "の", "こ", "え"], "reverse": "えこのしむのきあ", "bg": "bg_beginner_3.png"},
        {"word": "ふゆのさむいあさ", "ruby": ["ふ", "ゆ", "の", "さ", "む", "い", "あ", "さ"], "reverse": "さあいむさのゆふ", "bg": "bg_beginner_1.png"},
        {"word": "みずうみのほとり", "ruby": ["み", "ず", "う", "み", "の", "ほ", "と", "り"], "reverse": "りとほのみうずみ", "bg": "bg_beginner_2.png"},
    ],
};

const SAMPLE_WORDS = {
    beginner: QUESTION_DATABASE.beginner.map(q => q.word),
    intermediate: QUESTION_DATABASE.intermediate.map(q => q.word),
    advanced: QUESTION_DATABASE.advanced.map(q => q.word)
};
