/**
 * Reversa Question Database (Theme Based)
 * 初級：2〜4文字
 * 中級：5〜7文字
 * 上級：8〜10文字
 */
const QUESTION_DATABASE = {
    beginner: [
        {"word": "いぬ", "ruby": ["い", "ぬ"], "reverse": "ぬい", "bg": "bg_beginner_1.png"},
        {"word": "ねこ", "ruby": ["ね", "こ"], "reverse": "こね", "bg": "bg_beginner_2.png"},
        {"word": "きつね", "ruby": ["き", "つ", "ね"], "reverse": "ねつき", "bg": "bg_beginner_3.png"},
        {"word": "さくら", "ruby": ["さ", "く", "ら"], "reverse": "らくさ", "bg": "bg_beginner_1.png"},
        {"word": "はし", "ruby": ["は", "し"], "reverse": "しは", "bg": "bg_beginner_2.png"},
        {"word": "りんご", "ruby": ["り", "ん", "ご"], "reverse": "ごんり", "bg": "bg_beginner_3.png"},
        {"word": "みかん", "ruby": ["み", "か", "ん"], "reverse": "んかみ", "bg": "bg_beginner_1.png"},
        {"word": "くるま", "ruby": ["く", "る", "ま"], "reverse": "まるく", "bg": "bg_beginner_2.png"},
        {"word": "めがね", "ruby": ["め", "が", "ね"], "reverse": "ねがめ", "bg": "bg_beginner_3.png"},
        {"word": "からす", "ruby": ["か", "ら", "す"], "reverse": "すらか", "bg": "bg_beginner_1.png"},
        {"word": "すずめ", "ruby": ["す", "ず", "め"], "reverse": "めずす", "bg": "bg_beginner_2.png"},
        {"word": "うさぎ", "ruby": ["う", "さ", "ぎ"], "reverse": "ぎさう", "bg": "bg_beginner_3.png"},
        {"word": "うし", "ruby": ["う", "し"], "reverse": "しう", "bg": "bg_beginner_1.png"},
        {"word": "とり", "ruby": ["と", "り"], "reverse": "りと", "bg": "bg_beginner_2.png"},
        {"word": "かめ", "ruby": ["か", "め"], "reverse": "めか", "bg": "bg_beginner_3.png"},
        {"word": "さる", "ruby": ["さ", "る"], "reverse": "るさ", "bg": "bg_beginner_1.png"},
        {"word": "へび", "ruby": ["へ", "び"], "reverse": "びへ", "bg": "bg_beginner_2.png"},
        {"word": "くま", "ruby": ["く", "ま"], "reverse": "まく", "bg": "bg_beginner_3.png"},
        {"word": "しか", "ruby": ["し", "か"], "reverse": "かし", "bg": "bg_beginner_1.png"},
        {"word": "あり", "ruby": ["あ", "り"], "reverse": "りあ", "bg": "bg_beginner_2.png"},
        {"word": "はな", "ruby": ["は", "な"], "reverse": "なは", "bg": "bg_beginner_3.png"},
        {"word": "きり", "ruby": ["き", "り"], "reverse": "りき", "bg": "bg_beginner_1.png"},
        {"word": "くじら", "ruby": ["く", "じ", "ら"], "reverse": "らじく", "bg": "bg_beginner_2.png"},
        {"word": "とら", "ruby": ["と", "ら"], "reverse": "らと", "bg": "bg_beginner_3.png"},
        {"word": "ひよこ", "ruby": ["ひ", "よ", "こ"], "reverse": "こよひ", "bg": "bg_beginner_1.png"},
        {"word": "かえる", "ruby": ["か", "え", "る"], "reverse": "るえか", "bg": "bg_beginner_2.png"},
        {"word": "めだか", "ruby": ["め", "だ", "か"], "reverse": "かだめ", "bg": "bg_beginner_3.png"},
        {"word": "さかな", "ruby": ["さ", "か", "な"], "reverse": "なかさ", "bg": "bg_beginner_1.png"},
        {"word": "ごはん", "ruby": ["ご", "は", "ん"], "reverse": "んはご", "bg": "bg_beginner_2.png"},
        {"word": "みず", "ruby": ["み", "ず"], "reverse": "ずみ", "bg": "bg_beginner_3.png"},
        {"word": "たまご", "ruby": ["た", "ま", "ご"], "reverse": "ごまた", "bg": "bg_beginner_1.png"},
        {"word": "うどん", "ruby": ["う", "ど", "ん"], "reverse": "んどう", "bg": "bg_beginner_2.png"},
        {"word": "そば", "ruby": ["そ", "ば"], "reverse": "ばそ", "bg": "bg_beginner_3.png"},
        {"word": "ぽてと", "ruby": ["ぽ", "て", "と"], "reverse": "とてぽ", "bg": "bg_beginner_1.png"},
        {"word": "つくえ", "ruby": ["つ", "く", "え"], "reverse": "えくつ", "bg": "bg_beginner_2.png"},
        {"word": "いす", "ruby": ["い", "す"], "reverse": "すい", "bg": "bg_beginner_3.png"},
        {"word": "ほん", "ruby": ["ほ", "ん"], "reverse": "んほ", "bg": "bg_beginner_1.png"},
        {"word": "かみ", "ruby": ["か", "み"], "reverse": "みか", "bg": "bg_beginner_2.png"},
        {"word": "かばん", "ruby": ["か", "ば", "ん"], "reverse": "んばか", "bg": "bg_beginner_3.png"},
        {"word": "くつ", "ruby": ["く", "つ"], "reverse": "つく", "bg": "bg_beginner_1.png"},
        {"word": "ふく", "ruby": ["ふ", "く"], "reverse": "くふ", "bg": "bg_beginner_2.png"},
        {"word": "かさ", "ruby": ["か", "さ"], "reverse": "さか", "bg": "bg_beginner_3.png"},
        {"word": "まど", "ruby": ["ま", "ど"], "reverse": "どま", "bg": "bg_beginner_1.png"},
        {"word": "かぎ", "ruby": ["か", "ぎ"], "reverse": "ぎか", "bg": "bg_beginner_2.png"},
        {"word": "さいふ", "ruby": ["さ", "い", "ふ"], "reverse": "ふいさ", "bg": "bg_beginner_3.png"},
        {"word": "そら", "ruby": ["そ", "ら"], "reverse": "らそ", "bg": "bg_beginner_1.png"},
        {"word": "うみ", "ruby": ["う", "み"], "reverse": "みう", "bg": "bg_beginner_2.png"},
        {"word": "やま", "ruby": ["や", "ま"], "reverse": "まや", "bg": "bg_beginner_3.png"},
        {"word": "もり", "ruby": ["も", "り"], "reverse": "りも", "bg": "bg_beginner_1.png"},
        {"word": "くも", "ruby": ["く", "も"], "reverse": "もく", "bg": "bg_beginner_2.png"},
        {"word": "つき", "ruby": ["つ", "き"], "reverse": "きつ", "bg": "bg_beginner_3.png"},
        {"word": "ほし", "ruby": ["ほ", "し"], "reverse": "しほ", "bg": "bg_beginner_1.png"},
        {"word": "にじ", "ruby": ["に", "じ"], "reverse": "じに", "bg": "bg_beginner_2.png"},
        {"word": "かぜ", "ruby": ["か", "ぜ"], "reverse": "ぜか", "bg": "bg_beginner_3.png"},
        {"word": "ゆき", "ruby": ["ゆ", "き"], "reverse": "きゆ", "bg": "bg_beginner_1.png"},
        {"word": "くさ", "ruby": ["く", "さ"], "reverse": "さく", "bg": "bg_beginner_2.png"},
        {"word": "かわ", "ruby": ["か", "わ"], "reverse": "わか", "bg": "bg_beginner_3.png"},
        {"word": "いけ", "ruby": ["い", "け"], "reverse": "けい", "bg": "bg_beginner_1.png"},
        {"word": "あか", "ruby": ["あ", "か"], "reverse": "かあ", "bg": "bg_beginner_2.png"},
        {"word": "あお", "ruby": ["あ", "お"], "reverse": "おあ", "bg": "bg_beginner_3.png"},
        {"word": "しろ", "ruby": ["し", "ろ"], "reverse": "ろし", "bg": "bg_beginner_1.png"},
        {"word": "くろ", "ruby": ["く", "ろ"], "reverse": "ろく", "bg": "bg_beginner_2.png"},
        {"word": "いえ", "ruby": ["い", "え"], "reverse": "えい", "bg": "bg_beginner_3.png"},
        {"word": "にわ", "ruby": ["に", "わ"], "reverse": "わに", "bg": "bg_beginner_1.png"},
        {"word": "まち", "ruby": ["ま", "ち"], "reverse": "ちま", "bg": "bg_beginner_2.png"},
        {"word": "うた", "ruby": ["う", "た"], "reverse": "たう", "bg": "bg_beginner_3.png"},
        {"word": "いま", "ruby": ["い", "ま"], "reverse": "まい", "bg": "bg_beginner_1.png"},
        {"word": "あさ", "ruby": ["あ", "さ"], "reverse": "さあ", "bg": "bg_beginner_2.png"},
        {"word": "ゆめ", "ruby": ["ゆ", "め"], "reverse": "めゆ", "bg": "bg_beginner_3.png"},
    ],
    intermediate: [
        {"word": "かたつむり", "ruby": ["か", "た", "つ", "む", "り"], "reverse": "りむつたか", "bg": "bg_beginner_1.png"},
        {"word": "ほととぎす", "ruby": ["ほ", "と", "と", "ぎ", "す"], "reverse": "すぎととほ", "bg": "bg_beginner_2.png"},
        {"word": "おぼろづき", "ruby": ["お", "ぼ", "ろ", "づ", "き"], "reverse": "きづろぼお", "bg": "bg_beginner_3.png"},
        {"word": "あきあかね", "ruby": ["あ", "き", "あ", "か", "ね"], "reverse": "ねかあきあ", "bg": "bg_beginner_1.png"},
        {"word": "しもばしら", "ruby": ["し", "も", "ば", "し", "ら"], "reverse": "らしばもし", "bg": "bg_beginner_2.png"},
        {"word": "こいのぼり", "ruby": ["こ", "い", "の", "ぼ", "り"], "reverse": "りぼのいこ", "bg": "bg_beginner_3.png"},
        {"word": "おとしだま", "ruby": ["お", "と", "し", "だ", "ま"], "reverse": "まだしとお", "bg": "bg_beginner_1.png"},
        {"word": "ひなまつり", "ruby": ["ひ", "な", "ま", "つ", "り"], "reverse": "りつまなひ", "bg": "bg_beginner_2.png"},
        {"word": "わらびもち", "ruby": ["わ", "ら", "び", "も", "ち"], "reverse": "ちもびらわ", "bg": "bg_beginner_3.png"},
        {"word": "かしわもち", "ruby": ["か", "し", "わ", "も", "ち"], "reverse": "ちもわしか", "bg": "bg_beginner_1.png"},
        {"word": "だいふくもち", "ruby": ["だ", "い", "ふ", "く", "も", "ち"], "reverse": "ちもくふいだ", "bg": "bg_beginner_2.png"},
        {"word": "ふゆげしき", "ruby": ["ふ", "ゆ", "げ", "し", "き"], "reverse": "きしげゆふ", "bg": "bg_beginner_3.png"},
        {"word": "つきみだんご", "ruby": ["つ", "き", "み", "だ", "ん", "ご"], "reverse": "ごんだみきつ", "bg": "bg_beginner_1.png"},
        {"word": "あまのがわ", "ruby": ["あ", "ま", "の", "が", "わ"], "reverse": "わがのまあ", "bg": "bg_beginner_2.png"},
        {"word": "あかいふね", "ruby": ["あ", "か", "い", "ふ", "ね"], "reverse": "ねふいかあ", "bg": "bg_beginner_3.png"},
        {"word": "あきのそら", "ruby": ["あ", "き", "の", "そ", "ら"], "reverse": "らそのきあ", "bg": "bg_beginner_1.png"},
        {"word": "はるのやま", "ruby": ["は", "る", "の", "や", "ま"], "reverse": "まやのるは", "bg": "bg_beginner_2.png"},
        {"word": "なつのみず", "ruby": ["な", "つ", "の", "み", "ず"], "reverse": "ずみのつな", "bg": "bg_beginner_3.png"},
        {"word": "ふゆのゆき", "ruby": ["ふ", "ゆ", "の", "ゆ", "き"], "reverse": "きゆのゆふ", "bg": "bg_beginner_1.png"},
        {"word": "つきのひかり", "ruby": ["つ", "き", "の", "ひ", "か", "り"], "reverse": "りかひのきつ", "bg": "bg_beginner_2.png"},
        {"word": "ほしのよる", "ruby": ["ほ", "し", "の", "よ", "る"], "reverse": "るよのしほ", "bg": "bg_beginner_3.png"},
        {"word": "あおいとり", "ruby": ["あ", "お", "い", "と", "り"], "reverse": "りといおあ", "bg": "bg_beginner_1.png"},
        {"word": "しろいくも", "ruby": ["し", "ろ", "い", "く", "も"], "reverse": "もくいろし", "bg": "bg_beginner_2.png"},
        {"word": "やまのみち", "ruby": ["や", "ま", "の", "み", "ち"], "reverse": "ちみのまや", "bg": "bg_beginner_3.png"},
        {"word": "うみのなみ", "ruby": ["う", "み", "の", "な", "み"], "reverse": "みなのみう", "bg": "bg_beginner_1.png"},
        {"word": "ひかるかぜ", "ruby": ["ひ", "か", "る", "か", "ぜ"], "reverse": "ぜかるかひ", "bg": "bg_beginner_2.png"},
        {"word": "きいろいはな", "ruby": ["き", "い", "ろ", "い", "は", "な"], "reverse": "なはいろいき", "bg": "bg_beginner_3.png"},
        {"word": "あかいりんご", "ruby": ["あ", "か", "い", "り", "ん", "ご"], "reverse": "ごんりいかあ", "bg": "bg_beginner_1.png"},
        {"word": "あまいみかん", "ruby": ["あ", "ま", "い", "み", "か", "ん"], "reverse": "んかみいまあ", "bg": "bg_beginner_2.png"},
        {"word": "まるいすいか", "ruby": ["ま", "る", "い", "す", "い", "か"], "reverse": "かいすいるま", "bg": "bg_beginner_3.png"},
        {"word": "ながいはし", "ruby": ["な", "が", "い", "は", "し"], "reverse": "しはいがな", "bg": "bg_beginner_1.png"},
        {"word": "まるいつくえ", "ruby": ["ま", "る", "い", "つ", "く", "え"], "reverse": "えくついるま", "bg": "bg_beginner_2.png"},
        {"word": "ひろいにわ", "ruby": ["ひ", "ろ", "い", "に", "わ"], "reverse": "わにいろひ", "bg": "bg_beginner_3.png"},
        {"word": "ふるいまち", "ruby": ["ふ", "る", "い", "ま", "ち"], "reverse": "ちまいるふ", "bg": "bg_beginner_1.png"},
        {"word": "たのしいうた", "ruby": ["た", "の", "し", "い", "う", "た"], "reverse": "たういしのた", "bg": "bg_beginner_2.png"},
        {"word": "きれいなえ", "ruby": ["き", "れ", "い", "な", "え"], "reverse": "えないれき", "bg": "bg_beginner_3.png"},
        {"word": "はやいくるま", "ruby": ["は", "や", "い", "く", "る", "ま"], "reverse": "まるくいやは", "bg": "bg_beginner_1.png"},
        {"word": "おもいかばん", "ruby": ["お", "も", "い", "か", "ば", "ん"], "reverse": "んばかいもお", "bg": "bg_beginner_2.png"},
        {"word": "ひろいうみ", "ruby": ["ひ", "ろ", "い", "う", "み"], "reverse": "みういろひ", "bg": "bg_beginner_3.png"},
        {"word": "あおいくるま", "ruby": ["あ", "お", "い", "く", "る", "ま"], "reverse": "まるくいおあ", "bg": "bg_beginner_1.png"},
        {"word": "やまびこのこえ", "ruby": ["や", "ま", "び", "こ", "の", "こ", "え"], "reverse": "えこのこびまや", "bg": "bg_beginner_2.png"},
        {"word": "あめあがりのそら", "ruby": ["あ", "め", "あ", "が", "り", "の", "そ", "ら"], "reverse": "らそのりがあめあ", "bg": "bg_beginner_3.png"},
        {"word": "もりのかくれんぼ", "ruby": ["も", "り", "の", "か", "く", "れ", "ん", "ぼ"], "reverse": "ぼんれくかのりも", "bg": "bg_beginner_1.png"},
        {"word": "さくらのつぼみ", "ruby": ["さ", "く", "ら", "の", "つ", "ぼ", "み"], "reverse": "みぼつのらくさ", "bg": "bg_beginner_2.png"},
        {"word": "あきのみかく", "ruby": ["あ", "き", "の", "み", "か", "く"], "reverse": "くかみのきあ", "bg": "bg_beginner_3.png"},
        {"word": "ひかりのわ", "ruby": ["ひ", "か", "り", "の", "わ"], "reverse": "わのりかひ", "bg": "bg_beginner_1.png"},
        {"word": "ふねのたび", "ruby": ["ふ", "ね", "の", "た", "び"], "reverse": "びたのねふ", "bg": "bg_beginner_2.png"},
        {"word": "そらのたび", "ruby": ["そ", "ら", "の", "た", "び"], "reverse": "びたのらそ", "bg": "bg_beginner_3.png"},
        {"word": "ゆめのなか", "ruby": ["ゆ", "め", "の", "な", "か"], "reverse": "かなのめゆ", "bg": "bg_beginner_1.png"},
        {"word": "あさのひかり", "ruby": ["あ", "さ", "の", "ひ", "か", "り"], "reverse": "りかひのさあ", "bg": "bg_beginner_2.png"},
    ],
    advanced: [
        {"word": "あまのがわきらきら", "ruby": ["あ", "ま", "の", "が", "わ", "き", "ら", "き", "ら"], "reverse": "らきらきわがのまあ", "bg": "bg_beginner_1.png"},
        {"word": "やまのうえのおてら", "ruby": ["や", "ま", "の", "う", "え", "の", "お", "て", "ら"], "reverse": "らておのえうのまや", "bg": "bg_beginner_2.png"},
        {"word": "あめあがりのにじ", "ruby": ["あ", "め", "あ", "が", "り", "の", "に", "じ"], "reverse": "じにのりがあめあ", "bg": "bg_beginner_3.png"},
        {"word": "もりのおんがくかい", "ruby": ["も", "り", "の", "お", "ん", "が", "く", "か", "い"], "reverse": "いかくがんおのりも", "bg": "bg_beginner_1.png"},
        {"word": "おひさまのひかり", "ruby": ["お", "ひ", "さ", "ま", "の", "ひ", "か", "り"], "reverse": "りかひのまさひお", "bg": "bg_beginner_2.png"},
        {"word": "うみのなかのさかな", "ruby": ["う", "み", "の", "な", "か", "の", "さ", "か", "な"], "reverse": "なかさのかなのみう", "bg": "bg_beginner_3.png"},
        {"word": "そらのうえのほし", "ruby": ["そ", "ら", "の", "う", "え", "の", "ほ", "し"], "reverse": "しほのえうのらそ", "bg": "bg_beginner_1.png"},
        {"word": "ひなまつりのうた", "ruby": ["ひ", "な", "ま", "つ", "り", "の", "う", "た"], "reverse": "たうのりつまなひ", "bg": "bg_beginner_2.png"},
        {"word": "こいのぼりのうた", "ruby": ["こ", "い", "の", "ぼ", "り", "の", "う", "た"], "reverse": "たうのりぼのいこ", "bg": "bg_beginner_3.png"},
        {"word": "あおぞらのしろいくも", "ruby": ["あ", "お", "ぞ", "ら", "の", "し", "ろ", "い", "く", "も"], "reverse": "もくいろしのらぞおあ", "bg": "bg_beginner_1.png"},
        {"word": "あかいはなのなまえ", "ruby": ["あ", "か", "い", "は", "な", "の", "な", "ま", "え"], "reverse": "えまなのなはいかあ", "bg": "bg_beginner_2.png"},
        {"word": "みどりのもりのなか", "ruby": ["み", "ど", "り", "の", "も", "り", "の", "な", "か"], "reverse": "かなのりものりどみ", "bg": "bg_beginner_3.png"},
        {"word": "きいろいくつのあと", "ruby": ["き", "い", "ろ", "い", "く", "つ", "の", "あ", "と"], "reverse": "とあのつくいろいき", "bg": "bg_beginner_1.png"},
        {"word": "くろいくものかげ", "ruby": ["く", "ろ", "い", "く", "も", "の", "か", "げ"], "reverse": "げかのもくいろく", "bg": "bg_beginner_2.png"},
        {"word": "あおいとりのはね", "ruby": ["あ", "お", "い", "と", "り", "の", "は", "ね"], "reverse": "ねはのりといおあ", "bg": "bg_beginner_3.png"},
        {"word": "しろいくまのゆめ", "ruby": ["し", "ろ", "い", "く", "ま", "の", "ゆ", "め"], "reverse": "めゆのまくいろし", "bg": "bg_beginner_1.png"},
        {"word": "はるのかぜのにおい", "ruby": ["は", "る", "の", "か", "ぜ", "の", "に", "お", "い"], "reverse": "いおにのぜかのるは", "bg": "bg_beginner_2.png"},
        {"word": "なつのうみのあおさ", "ruby": ["な", "つ", "の", "う", "み", "の", "あ", "お", "さ"], "reverse": "さおあのみうのつな", "bg": "bg_beginner_3.png"},
        {"word": "あきのやまのいろ", "ruby": ["あ", "き", "の", "や", "ま", "の", "い", "ろ"], "reverse": "ろいのまやのきあ", "bg": "bg_beginner_1.png"},
        {"word": "あしたのゆめのなか", "ruby": ["あ", "し", "た", "の", "ゆ", "め", "の", "な", "か"], "reverse": "かなのめゆのたしあ", "bg": "bg_beginner_2.png"},
        {"word": "きのうのよるのほし", "ruby": ["き", "の", "う", "の", "よ", "る", "の", "ほ", "し"], "reverse": "しほのるよのうのき", "bg": "bg_beginner_3.png"},
        {"word": "おとなのひそひそはなし", "ruby": ["お", "と", "な", "の", "ひ", "そ", "ひ", "そ", "は", "な", "し"], "reverse": "しなはそひそひのなとお", "bg": "bg_beginner_1.png"},
        {"word": "ひみつのたからもの", "ruby": ["ひ", "み", "つ", "の", "た", "か", "ら", "も", "の"], "reverse": "のもらかたのつみひ", "bg": "bg_beginner_2.png"},
        {"word": "ふしぎなまほうのつえ", "ruby": ["ふ", "し", "ぎ", "な", "ま", "ほ", "う", "の", "つ", "え"], "reverse": "えつのうほまなぎしふ", "bg": "bg_beginner_3.png"},
        {"word": "たのしいおまつりのよる", "ruby": ["た", "の", "し", "い", "お", "ま", "つ", "り", "の", "よ", "る"], "reverse": "るよのりつまおいしのた", "bg": "bg_beginner_1.png"},
        {"word": "きれいなみなとのひかり", "ruby": ["き", "れ", "い", "な", "み", "な", "と", "の", "ひ", "か", "り"], "reverse": "りかひのとなみないれき", "bg": "bg_beginner_2.png"},
        {"word": "しずかなもりのなか", "ruby": ["し", "ず", "か", "な", "も", "り", "の", "な", "か"], "reverse": "かなのりもなかずし", "bg": "bg_beginner_3.png"},
        {"word": "あかいりんごをたべる", "ruby": ["あ", "か", "い", "り", "ん", "ご", "を", "た", "べ", "る"], "reverse": "るべたをごんりいかあ", "bg": "bg_beginner_1.png"},
        {"word": "あまいみかんをむく", "ruby": ["あ", "ま", "い", "み", "か", "ん", "を", "む", "く"], "reverse": "くむをんかみいまあ", "bg": "bg_beginner_2.png"},
        {"word": "まるいすいかをきる", "ruby": ["ま", "る", "い", "す", "い", "か", "を", "き", "る"], "reverse": "るきをかいすいるま", "bg": "bg_beginner_3.png"},
        {"word": "あかいふねにのる", "ruby": ["あ", "か", "い", "ふ", "ね", "に", "の", "る"], "reverse": "るのにねふいかあ", "bg": "bg_beginner_1.png"},
        {"word": "あおいくるまをまつ", "ruby": ["あ", "お", "い", "く", "る", "ま", "を", "ま", "つ"], "reverse": "つまをまるくいおあ", "bg": "bg_beginner_2.png"},
        {"word": "きれいなはなをみる", "ruby": ["き", "れ", "い", "な", "は", "な", "を", "み", "る"], "reverse": "るみをなはないれき", "bg": "bg_beginner_3.png"},
        {"word": "たのしいうたをうたう", "ruby": ["た", "の", "し", "い", "う", "た", "を", "う", "た", "う"], "reverse": "うたうをたういしのた", "bg": "bg_beginner_1.png"},
        {"word": "ひろいうみをわたる", "ruby": ["ひ", "ろ", "い", "う", "み", "を", "わ", "た", "る"], "reverse": "るたわをみういろひ", "bg": "bg_beginner_2.png"},
        {"word": "たかいやまにのぼる", "ruby": ["た", "か", "い", "や", "ま", "に", "の", "ぼ", "る"], "reverse": "るぼのにまやいかた", "bg": "bg_beginner_3.png"},
        {"word": "あおいとりをさがす", "ruby": ["あ", "お", "い", "と", "り", "を", "さ", "が", "す"], "reverse": "すがさをりといおあ", "bg": "bg_beginner_1.png"},
        {"word": "ふるいまちをあるく", "ruby": ["ふ", "る", "い", "ま", "ち", "を", "あ", "る", "く"], "reverse": "くるあをちまいるふ", "bg": "bg_beginner_2.png"},
        {"word": "しろいくもをみあげる", "ruby": ["し", "ろ", "い", "く", "も", "を", "み", "あ", "げ", "る"], "reverse": "るげあみをもくいろし", "bg": "bg_beginner_3.png"},
        {"word": "あさのひかりをあびる", "ruby": ["あ", "さ", "の", "ひ", "か", "り", "を", "あ", "び", "る"], "reverse": "るびあをりかひのさあ", "bg": "bg_beginner_1.png"},
        {"word": "ゆめのなかであそぶ", "ruby": ["ゆ", "め", "の", "な", "か", "で", "あ", "そ", "ぶ"], "reverse": "ぶそあでかなのめゆ", "bg": "bg_beginner_2.png"},
        {"word": "ほしのよるをまつ", "ruby": ["ほ", "し", "の", "よ", "る", "を", "ま", "つ"], "reverse": "つまをるよのしほ", "bg": "bg_beginner_3.png"},
        {"word": "はるのひかりのなか", "ruby": ["は", "る", "の", "ひ", "か", "り", "の", "な", "か"], "reverse": "かなのりかひのるは", "bg": "bg_beginner_1.png"},
        {"word": "なつのなみのこえ", "ruby": ["な", "つ", "の", "な", "み", "の", "こ", "え"], "reverse": "えこのみなのつな", "bg": "bg_beginner_2.png"},
        {"word": "あきのむしのこえ", "ruby": ["あ", "き", "の", "む", "し", "の", "こ", "え"], "reverse": "えこのしむのきあ", "bg": "bg_beginner_3.png"},
        {"word": "ふゆのさむいあさ", "ruby": ["ふ", "ゆ", "の", "さ", "む", "い", "あ", "さ"], "reverse": "さあいむさのゆふ", "bg": "bg_beginner_1.png"},
        {"word": "みずうみのほとり", "ruby": ["み", "ず", "う", "み", "の", "ほ", "と", "り"], "reverse": "りとほのみうずみ", "bg": "bg_beginner_2.png"},
    ],
};

const SAMPLE_WORDS = {
    beginner: QUESTION_DATABASE.beginner.map(q => q.word),
    intermediate: QUESTION_DATABASE.intermediate.map(q => q.word),
    advanced: QUESTION_DATABASE.advanced.map(q => q.word)
};
