/**
 * Reversa Question Database (Theme Based)
 * 初級：2〜4文字の日常語
 * 中級：4〜5文字の少し長い単語や自然の言葉
 * 上級：5〜7文字の難易度の高い単語、熟語、挨拶
 */
const QUESTION_DATABASE = {
    beginner: [
        {"word": "いぬ", "ruby": ["い", "ぬ"], "reverse": "ぬい", "bg": "bg_beginner_1.png"},
        {"word": "ねこ", "ruby": ["ね", "こ"], "reverse": "こね", "bg": "bg_beginner_2.png"},
        {"word": "きつね", "ruby": ["き", "つ", "ね"], "reverse": "ねつき", "bg": "bg_beginner_3.png"},
        {"word": "さくら", "ruby": ["さ", "く", "ら"], "reverse": "らくさ", "bg": "bg_beginner_1.png"},
        {"word": "みかづき", "ruby": ["み", "か", "づ", "き"], "reverse": "きづかみ", "bg": "bg_beginner_2.png"},
        {"word": "とうろう", "ruby": ["と", "う", "ろ", "う"], "reverse": "うろうと", "bg": "bg_beginner_3.png"},
        {"word": "すぎのき", "ruby": ["す", "ぎ", "の", "き"], "reverse": "きのぎす", "bg": "bg_beginner_1.png"},
        {"word": "はし", "ruby": ["は", "し"], "reverse": "しは", "bg": "bg_beginner_2.png"},
        {"word": "げんそう", "ruby": ["げ", "ん", "そ", "う"], "reverse": "うそんげ", "bg": "bg_beginner_3.png"},
        {"word": "りんご", "ruby": ["り", "ん", "ご"], "reverse": "ごんり", "bg": "bg_beginner_1.png"},
        {"word": "みかん", "ruby": ["み", "か", "ん"], "reverse": "んかみ", "bg": "bg_beginner_2.png"},
        {"word": "くるま", "ruby": ["く", "る", "ま"], "reverse": "まるく", "bg": "bg_beginner_3.png"},
        {"word": "めがね", "ruby": ["め", "が", "ね"], "reverse": "ねがめ", "bg": "bg_beginner_1.png"},
        {"word": "テレビ", "ruby": ["て", "れ", "び"], "reverse": "びれて", "bg": "bg_beginner_2.png"},
        {"word": "ピアノ", "ruby": ["ぴ", "あ", "の"], "reverse": "のあぴ", "bg": "bg_beginner_3.png"},
        {"word": "カラス", "ruby": ["か", "ら", "す"], "reverse": "すらか", "bg": "bg_beginner_1.png"},
        {"word": "すずめ", "ruby": ["す", "ず", "め"], "reverse": "めずす", "bg": "bg_beginner_2.png"},
        {"word": "うさぎ", "ruby": ["う", "さ", "ぎ"], "reverse": "ぎさう", "bg": "bg_beginner_3.png"},
        {"word": "でんわ", "ruby": ["で", "ん", "わ"], "reverse": "わんで", "bg": "bg_beginner_1.png"},
        {"word": "カメラ", "ruby": ["か", "め", "ら"], "reverse": "らめか", "bg": "bg_beginner_2.png"},
        {"word": "メロン", "ruby": ["め", "ろ", "ん"], "reverse": "んろめ", "bg": "bg_beginner_3.png"},
        {"word": "いちご", "ruby": ["い", "ち", "ご"], "reverse": "ごちい", "bg": "bg_beginner_1.png"},
        {"word": "すいか", "ruby": ["す", "い", "か"], "reverse": "かいす", "bg": "bg_beginner_2.png"},
        {"word": "きっぷ", "ruby": ["き", "っ", "ぷ"], "reverse": "ぷっき", "bg": "bg_beginner_3.png"},
        {"word": "きっさてん", "ruby": ["き", "っ", "さ", "て", "ん"], "reverse": "んてさっき", "bg": "bg_beginner_1.png"},
        {"word": "えんぴつ", "ruby": ["え", "ん", "ぴ", "つ"], "reverse": "つぴんえ", "bg": "bg_beginner_2.png"},
        {"word": "とけい", "ruby": ["と", "け", "い"], "reverse": "いけと", "bg": "bg_beginner_3.png"},
        {"word": "うし", "ruby": ["う", "し"], "reverse": "しう", "bg": "bg_beginner_1.png"},
        {"word": "とり", "ruby": ["と", "り"], "reverse": "りと", "bg": "bg_beginner_2.png"},
        {"word": "かめ", "ruby": ["か", "め"], "reverse": "めか", "bg": "bg_beginner_3.png"},
        {"word": "さる", "ruby": ["さ", "る"], "reverse": "るさ", "bg": "bg_beginner_1.png"},
        {"word": "へび", "ruby": ["へ", "び"], "reverse": "びへ", "bg": "bg_beginner_2.png"},
        {"word": "くま", "ruby": ["く", "ま"], "reverse": "まく", "bg": "bg_beginner_3.png"},
        {"word": "しか", "ruby": ["し", "か"], "reverse": "かし", "bg": "bg_beginner_1.png"},
        {"word": "あり", "ruby": ["あ", "り"], "reverse": "りあ", "bg": "bg_beginner_2.png"},
        {"word": "はな", "ruby": ["は", "な"], "reverse": "なは", "bg": "bg_beginner_3.png"},
        {"word": "きり", "ruby": ["き", "り"], "reverse": "りき", "bg": "bg_beginner_1.png"},
        {"word": "くじら", "ruby": ["く", "じ", "ら"], "reverse": "らじく", "bg": "bg_beginner_2.png"},
        {"word": "とら", "ruby": ["と", "ら"], "reverse": "らと", "bg": "bg_beginner_3.png"},
        {"word": "らいおん", "ruby": ["ら", "い", "お", "ん"], "reverse": "んおいら", "bg": "bg_beginner_1.png"},
        {"word": "ひよこ", "ruby": ["ひ", "よ", "こ"], "reverse": "こよひ", "bg": "bg_beginner_2.png"},
        {"word": "ぺんぎん", "ruby": ["ぺ", "ん", "ぎ", "ん"], "reverse": "んぎんぺ", "bg": "bg_beginner_3.png"},
        {"word": "パン", "ruby": ["ぱ", "ん"], "reverse": "んぱ", "bg": "bg_beginner_1.png"},
        {"word": "すし", "ruby": ["す", "し"], "reverse": "しす", "bg": "bg_beginner_2.png"},
        {"word": "もち", "ruby": ["も", "ち"], "reverse": "ちも", "bg": "bg_beginner_3.png"},
        {"word": "あめ", "ruby": ["あ", "め"], "reverse": "めあ", "bg": "bg_beginner_1.png"},
        {"word": "にく", "ruby": ["に", "く"], "reverse": "くに", "bg": "bg_beginner_2.png"},
        {"word": "さかな", "ruby": ["さ", "か", "な"], "reverse": "なかさ", "bg": "bg_beginner_3.png"},
        {"word": "ごはん", "ruby": ["ご", "は", "ん"], "reverse": "んはご", "bg": "bg_beginner_1.png"},
        {"word": "おちゃ", "ruby": ["お", "ちゃ"], "reverse": "ちゃお", "bg": "bg_beginner_2.png"},
        {"word": "みず", "ruby": ["み", "ず"], "reverse": "ずみ", "bg": "bg_beginner_3.png"},
        {"word": "たまご", "ruby": ["た", "ま", "ご"], "reverse": "ごまた", "bg": "bg_beginner_1.png"},
        {"word": "うどん", "ruby": ["う", "ど", "ん"], "reverse": "んどう", "bg": "bg_beginner_2.png"},
        {"word": "そば", "ruby": ["そ", "ば"], "reverse": "ばそ", "bg": "bg_beginner_3.png"},
        {"word": "ぽてと", "ruby": ["ぽ", "て", "と"], "reverse": "とてぽ", "bg": "bg_beginner_1.png"},
        {"word": "つくえ", "ruby": ["つ", "く", "え"], "reverse": "えくつ", "bg": "bg_beginner_2.png"},
        {"word": "いす", "ruby": ["い", "す"], "reverse": "すい", "bg": "bg_beginner_3.png"},
        {"word": "ほん", "ruby": ["ほ", "ん"], "reverse": "んほ", "bg": "bg_beginner_1.png"},
        {"word": "かみ", "ruby": ["か", "み"], "reverse": "みか", "bg": "bg_beginner_2.png"},
        {"word": "かばん", "ruby": ["か", "ば", "ん"], "reverse": "んばか", "bg": "bg_beginner_3.png"},
        {"word": "くつ", "ruby": ["く", "つ"], "reverse": "つく", "bg": "bg_beginner_1.png"},
        {"word": "ふく", "ruby": ["ふ", "く"], "reverse": "くふ", "bg": "bg_beginner_2.png"},
        {"word": "かさ", "ruby": ["か", "さ"], "reverse": "さか", "bg": "bg_beginner_3.png"},
        {"word": "まど", "ruby": ["ま", "ど"], "reverse": "どま", "bg": "bg_beginner_1.png"},
        {"word": "ドア", "ruby": ["ど", "あ"], "reverse": "あど", "bg": "bg_beginner_2.png"},
        {"word": "かぎ", "ruby": ["か", "ぎ"], "reverse": "ぎか", "bg": "bg_beginner_3.png"},
        {"word": "さいふ", "ruby": ["さ", "い", "ふ"], "reverse": "ふいさ", "bg": "bg_beginner_1.png"},
        {"word": "ふで", "ruby": ["ふ", "で"], "reverse": "でふ", "bg": "bg_beginner_2.png"},
        {"word": "のり", "ruby": ["の", "り"], "reverse": "りの", "bg": "bg_beginner_3.png"},
        {"word": "はさみ", "ruby": ["は", "さ", "み"], "reverse": "みさは", "bg": "bg_beginner_1.png"},
        {"word": "そら", "ruby": ["そ", "ら"], "reverse": "らそ", "bg": "bg_beginner_2.png"},
        {"word": "うみ", "ruby": ["う", "み"], "reverse": "みう", "bg": "bg_beginner_3.png"},
        {"word": "やま", "ruby": ["や", "ま"], "reverse": "まや", "bg": "bg_beginner_1.png"},
        {"word": "もり", "ruby": ["も", "り"], "reverse": "りも", "bg": "bg_beginner_2.png"},
        {"word": "くも", "ruby": ["く", "も"], "reverse": "もく", "bg": "bg_beginner_3.png"},
        {"word": "つき", "ruby": ["つ", "き"], "reverse": "きつ", "bg": "bg_beginner_1.png"},
        {"word": "ほし", "ruby": ["ほ", "し"], "reverse": "しほ", "bg": "bg_beginner_2.png"},
        {"word": "にじ", "ruby": ["に", "じ"], "reverse": "じに", "bg": "bg_beginner_3.png"},
        {"word": "かぜ", "ruby": ["か", "ぜ"], "reverse": "ぜか", "bg": "bg_beginner_1.png"},
        {"word": "ゆき", "ruby": ["ゆ", "き"], "reverse": "きゆ", "bg": "bg_beginner_2.png"},
        {"word": "くさ", "ruby": ["く", "さ"], "reverse": "さく", "bg": "bg_beginner_3.png"},
        {"word": "かわ", "ruby": ["か", "わ"], "reverse": "わか", "bg": "bg_beginner_1.png"},
        {"word": "いけ", "ruby": ["い", "け"], "reverse": "けい", "bg": "bg_beginner_2.png"},
        {"word": "たいよう", "ruby": ["た", "い", "よ", "う"], "reverse": "うよいた", "bg": "bg_beginner_3.png"},
        {"word": "め", "ruby": ["め"], "reverse": "め", "bg": "bg_beginner_1.png"},
        {"word": "みみ", "ruby": ["み", "み"], "reverse": "みみ", "bg": "bg_beginner_2.png"},
        {"word": "くち", "ruby": ["く", "ち"], "reverse": "ちく", "bg": "bg_beginner_3.png"},
        {"word": "て", "ruby": ["て"], "reverse": "て", "bg": "bg_beginner_1.png"},
        {"word": "あし", "ruby": ["あ", "し"], "reverse": "しあ", "bg": "bg_beginner_2.png"},
        {"word": "かた", "ruby": ["か", "た"], "reverse": "たか", "bg": "bg_beginner_3.png"},
        {"word": "こし", "ruby": ["こ", "し"], "reverse": "しこ", "bg": "bg_beginner_1.png"},
        {"word": "ゆび", "ruby": ["ゆ", "び"], "reverse": "びゆ", "bg": "bg_beginner_2.png"},
        {"word": "つめ", "ruby": ["つ", "め"], "reverse": "めつ", "bg": "bg_beginner_3.png"},
        {"word": "いろ", "ruby": ["い", "ろ"], "reverse": "ろい", "bg": "bg_beginner_1.png"},
        {"word": "あか", "ruby": ["あ", "か"], "reverse": "かあ", "bg": "bg_beginner_2.png"},
        {"word": "あお", "ruby": ["あ", "お"], "reverse": "おあ", "bg": "bg_beginner_3.png"},
        {"word": "しろ", "ruby": ["し", "ろ"], "reverse": "ろし", "bg": "bg_beginner_1.png"},
        {"word": "くろ", "ruby": ["く", "ろ"], "reverse": "ろく", "bg": "bg_beginner_2.png"},
        {"word": "いえ", "ruby": ["い", "え"], "reverse": "えい", "bg": "bg_beginner_3.png"},
        {"word": "にわ", "ruby": ["に", "わ"], "reverse": "わに", "bg": "bg_beginner_1.png"},
    ],
    intermediate: [
        {"word": "ひまわり", "ruby": ["ひ", "ま", "わ", "り"], "reverse": "りわまひ", "bg": "bg_beginner_1.png"},
        {"word": "あさがお", "ruby": ["あ", "さ", "が", "お"], "reverse": "おがさあ", "bg": "bg_beginner_2.png"},
        {"word": "うぐいす", "ruby": ["う", "ぐ", "い", "す"], "reverse": "すいぐう", "bg": "bg_beginner_3.png"},
        {"word": "ゆうやけ", "ruby": ["ゆ", "う", "や", "け"], "reverse": "けやうゆ", "bg": "bg_beginner_1.png"},
        {"word": "どうぶつ", "ruby": ["ど", "う", "ぶ", "つ"], "reverse": "つぶうど", "bg": "bg_beginner_2.png"},
        {"word": "ひこうき", "ruby": ["ひ", "こ", "う", "き"], "reverse": "きうこひ", "bg": "bg_beginner_3.png"},
        {"word": "カフェイン", "ruby": ["か", "ふぇ", "い", "ん"], "reverse": "んいふぇか", "bg": "bg_beginner_1.png"},
        {"word": "おまつり", "ruby": ["お", "ま", "つ", "り"], "reverse": "りつまお", "bg": "bg_beginner_2.png"},
        {"word": "にちよう", "ruby": ["に", "ち", "よ", "う"], "reverse": "うよちに", "bg": "bg_beginner_3.png"},
        {"word": "たいよう", "ruby": ["た", "い", "よ", "う"], "reverse": "うよいた", "bg": "bg_beginner_1.png"},
        {"word": "ふじさん", "ruby": ["ふ", "じ", "さ", "ん"], "reverse": "んさじふ", "bg": "bg_beginner_2.png"},
        {"word": "ネクタイ", "ruby": ["ね", "く", "た", "い"], "reverse": "いたくね", "bg": "bg_beginner_3.png"},
        {"word": "にんじん", "ruby": ["に", "ん", "じ", "ん"], "reverse": "んじんに", "bg": "bg_beginner_1.png"},
        {"word": "さんたく", "ruby": ["さ", "ん", "た", "く"], "reverse": "くたんさ", "bg": "bg_beginner_2.png"},
        {"word": "おにぎり", "ruby": ["お", "に", "ぎ", "り"], "reverse": "りぎにお", "bg": "bg_beginner_3.png"},
        {"word": "かいもの", "ruby": ["か", "い", "も", "の"], "reverse": "のもいか", "bg": "bg_beginner_1.png"},
        {"word": "おべんとう", "ruby": ["お", "べ", "ん", "と", "う"], "reverse": "うとんべお", "bg": "bg_beginner_2.png"},
        {"word": "すべりだい", "ruby": ["す", "べ", "り", "だ", "い"], "reverse": "いだりべす", "bg": "bg_beginner_3.png"},
        {"word": "としょかん", "ruby": ["と", "しょ", "か", "ん"], "reverse": "んかしょと", "bg": "bg_beginner_1.png"},
        {"word": "じてんしゃ", "ruby": ["じ", "て", "ん", "しゃ"], "reverse": "しゃんてじ", "bg": "bg_beginner_2.png"},
        {"word": "のみもの", "ruby": ["の", "み", "も", "の"], "reverse": "のもみの", "bg": "bg_beginner_3.png"},
        {"word": "あさごはん", "ruby": ["あ", "さ", "ご", "は", "ん"], "reverse": "んはごさあ", "bg": "bg_beginner_1.png"},
        {"word": "ひるごはん", "ruby": ["ひ", "る", "ご", "は", "ん"], "reverse": "んはごるひ", "bg": "bg_beginner_2.png"},
        {"word": "ばんごはん", "ruby": ["ば", "ん", "ご", "は", "ん"], "reverse": "んはごんば", "bg": "bg_beginner_3.png"},
        {"word": "おやつ", "ruby": ["お", "や", "つ"], "reverse": "つやお", "bg": "bg_beginner_1.png"},
        {"word": "はみがき", "ruby": ["は", "み", "が", "き"], "reverse": "きがみは", "bg": "bg_beginner_2.png"},
        {"word": "おふろ", "ruby": ["お", "ふ", "ろ"], "reverse": "ろふお", "bg": "bg_beginner_3.png"},
        {"word": "パジャマ", "ruby": ["ぱ", "じゃ", "ま"], "reverse": "まじゃぱ", "bg": "bg_beginner_1.png"},
        {"word": "ふとん", "ruby": ["ふ", "と", "ん"], "reverse": "んとふ", "bg": "bg_beginner_2.png"},
        {"word": "まくら", "ruby": ["ま", "く", "ら"], "reverse": "らくま", "bg": "bg_beginner_3.png"},
        {"word": "さんぽ", "ruby": ["さ", "ん", "ぽ"], "reverse": "ぽんさ", "bg": "bg_beginner_1.png"},
        {"word": "あそび", "ruby": ["あ", "そ", "び"], "reverse": "びそあ", "bg": "bg_beginner_2.png"},
        {"word": "べんきょう", "ruby": ["べ", "ん", "きょ", "う"], "reverse": "うきょんべ", "bg": "bg_beginner_3.png"},
        {"word": "せんせい", "ruby": ["せ", "ん", "せ", "い"], "reverse": "いせんせ", "bg": "bg_beginner_1.png"},
        {"word": "ともだち", "ruby": ["と", "も", "だ", "ち"], "reverse": "ちだもと", "bg": "bg_beginner_2.png"},
        {"word": "がっこう", "ruby": ["が", "っ", "こ", "う"], "reverse": "うこっが", "bg": "bg_beginner_3.png"},
        {"word": "きょうしつ", "ruby": ["きょ", "う", "し", "つ"], "reverse": "つしうきょ", "bg": "bg_beginner_1.png"},
        {"word": "えんぴつ", "ruby": ["え", "ん", "ぴ", "つ"], "reverse": "つぴんえ", "bg": "bg_beginner_2.png"},
        {"word": "けしごむ", "ruby": ["け", "し", "ご", "む"], "reverse": "むごしけ", "bg": "bg_beginner_3.png"},
        {"word": "教科書", "ruby": ["きょ", "う", "か", "しょ"], "reverse": "しょかうきょ", "bg": "bg_beginner_1.png"},
        {"word": "図書室", "ruby": ["と", "しょ", "し", "つ"], "reverse": "つししょと", "bg": "bg_beginner_2.png"},
        {"word": "校庭", "ruby": ["こ", "う", "て", "い"], "reverse": "いてうこ", "bg": "bg_beginner_3.png"},
        {"word": "公園", "ruby": ["こ", "う", "え", "ん"], "reverse": "んえうこ", "bg": "bg_beginner_1.png"},
        {"word": "電車", "ruby": ["で", "ん", "しゃ"], "reverse": "しゃんで", "bg": "bg_beginner_2.png"},
        {"word": "バス", "ruby": ["ば", "す"], "reverse": "すば", "bg": "bg_beginner_3.png"},
        {"word": "飛行機", "ruby": ["ひ", "こ", "う", "き"], "reverse": "きうこひ", "bg": "bg_beginner_1.png"},
        {"word": "船", "ruby": ["ふ", "ね"], "reverse": "ねふ", "bg": "bg_beginner_2.png"},
        {"word": "自転車", "ruby": ["じ", "て", "ん", "しゃ"], "reverse": "しゃんてじ", "bg": "bg_beginner_3.png"},
        {"word": "信号", "ruby": ["し", "ん", "ご", "う"], "reverse": "うごんし", "bg": "bg_beginner_1.png"},
        {"word": "駅", "ruby": ["え", "き"], "reverse": "きえ", "bg": "bg_beginner_2.png"},
        {"word": "商店街", "ruby": ["しょ", "う", "て", "ん", "が", "い"], "reverse": "いがんてうしょ", "bg": "bg_beginner_3.png"},
        {"word": "パン屋", "ruby": ["ぱ", "ん", "や"], "reverse": "やんぱ", "bg": "bg_beginner_1.png"},
        {"word": "本屋", "ruby": ["ほ", "ん", "や"], "reverse": "やんほ", "bg": "bg_beginner_2.png"},
        {"word": "花屋", "ruby": ["は", "な", "や"], "reverse": "やなは", "bg": "bg_beginner_3.png"},
        {"word": "魚屋", "ruby": ["さ", "か", "な", "や"], "reverse": "やなかさ", "bg": "bg_beginner_1.png"},
        {"word": "八百屋", "ruby": ["や", "お", "や"], "reverse": "やおや", "bg": "bg_beginner_2.png"},
        {"word": "遊園地", "ruby": ["ゆ", "う", "え", "ん", "ち"], "reverse": "ちんえうゆ", "bg": "bg_beginner_3.png"},
        {"word": "動物園", "ruby": ["ど", "う", "ぶ", "つ", "え", "ん"], "reverse": "んえつぶうど", "bg": "bg_beginner_1.png"},
        {"word": "水族館", "ruby": ["す", "い", "ぞ", "く", "か", "ん"], "reverse": "んかくぞいす", "bg": "bg_beginner_2.png"},
        {"word": "美術館", "ruby": ["び", "じゅ", "つ", "か", "ん"], "reverse": "んかつじゅび", "bg": "bg_beginner_3.png"},
        {"word": "博物館", "ruby": ["は", "く", "ぶ", "つ", "か", "ん"], "reverse": "んかつぶくは", "bg": "bg_beginner_1.png"},
        {"word": "お祭り", "ruby": ["お", "ま", "つ", "り"], "reverse": "りつまお", "bg": "bg_beginner_2.png"},
        {"word": "春休み", "ruby": ["は", "る", "や", "す", "み"], "reverse": "みすやるは", "bg": "bg_beginner_3.png"},
        {"word": "夏休み", "ruby": ["な", "つ", "や", "す", "み"], "reverse": "みすやつな", "bg": "bg_beginner_1.png"},
        {"word": "秋休み", "ruby": ["あ", "き", "や", "す", "み"], "reverse": "みすやきあ", "bg": "bg_beginner_2.png"},
        {"word": "冬休み", "ruby": ["ふ", "ゆ", "や", "す", "み"], "reverse": "みすやゆふ", "bg": "bg_beginner_3.png"},
        {"word": "誕生日", "ruby": ["た", "ん", "じょ", "う", "び"], "reverse": "びうじょんた", "bg": "bg_beginner_1.png"},
        {"word": "お正月", "ruby": ["お", "しょ", "う", "が", "つ"], "reverse": "つがうしょお", "bg": "bg_beginner_2.png"},
        {"word": "クリスマス", "ruby": ["く", "り", "す", "ま", "す"], "reverse": "すますりく", "bg": "bg_beginner_3.png"},
        {"word": "ひな祭り", "ruby": ["ひ", "な", "ま", "つ", "り"], "reverse": "りつまなひ", "bg": "bg_beginner_1.png"},
        {"word": "七夕", "ruby": ["た", "な", "ば", "た"], "reverse": "たばなた", "bg": "bg_beginner_2.png"},
        {"word": "お盆", "ruby": ["お", "ぼ", "ん"], "reverse": "んぼお", "bg": "bg_beginner_3.png"},
        {"word": "台風", "ruby": ["た", "い", "ふ", "う"], "reverse": "うふいた", "bg": "bg_beginner_1.png"},
        {"word": "地震", "ruby": ["じ", "し", "ん"], "reverse": "んしじ", "bg": "bg_beginner_2.png"},
        {"word": "雷", "ruby": ["か", "み", "な", "り"], "reverse": "りなみか", "bg": "bg_beginner_3.png"},
        {"word": "虹", "ruby": ["に", "じ"], "reverse": "じに", "bg": "bg_beginner_1.png"},
        {"word": "夕立", "ruby": ["ゆ", "う", "だ", "ち"], "reverse": "ちだうゆ", "bg": "bg_beginner_2.png"},
        {"word": "あじさい", "ruby": ["あ", "じ", "さ", "い"], "reverse": "いさじあ", "bg": "bg_beginner_3.png"},
        {"word": "コスモス", "ruby": ["こ", "す", "も", "す"], "reverse": "すもすこ", "bg": "bg_beginner_1.png"},
        {"word": "たんぽぽ", "ruby": ["た", "ん", "ぽ", "ぽ"], "reverse": "ぽぽんた", "bg": "bg_beginner_2.png"},
        {"word": "いちょう", "ruby": ["い", "ちょ", "う"], "reverse": "うちょい", "bg": "bg_beginner_3.png"},
        {"word": "もみじ", "ruby": ["も", "み", "じ"], "reverse": "じみも", "bg": "bg_beginner_1.png"},
        {"word": "さくら", "ruby": ["さ", "く", "ら"], "reverse": "らくさ", "bg": "bg_beginner_2.png"},
        {"word": "うめ", "ruby": ["う", "め"], "reverse": "めう", "bg": "bg_beginner_3.png"},
        {"word": "松の木", "ruby": ["ま", "つ", "の", "き"], "reverse": "きのつま", "bg": "bg_beginner_1.png"},
        {"word": "富士山", "ruby": ["ふ", "じ", "さ", "ん"], "reverse": "んさじふ", "bg": "bg_beginner_2.png"},
        {"word": "琵琶湖", "ruby": ["び", "わ", "こ"], "reverse": "こわび", "bg": "bg_beginner_3.png"},
        {"word": "利根川", "ruby": ["と", "ね", "が", "わ"], "reverse": "わがねと", "bg": "bg_beginner_1.png"},
        {"word": "瀬戸内海", "ruby": ["せ", "と", "な", "い", "か", "い"], "reverse": "いかいなとせ", "bg": "bg_beginner_2.png"},
        {"word": "日本海", "ruby": ["に", "ほ", "ん", "か", "い"], "reverse": "いかんほに", "bg": "bg_beginner_3.png"},
    ],
    advanced: [
        {"word": "なつやすみ", "ruby": ["な", "つ", "や", "す", "み"], "reverse": "みすやつな", "bg": "bg_beginner_1.png"},
        {"word": "しあわせな", "ruby": ["し", "あ", "わ", "せ", "な"], "reverse": "なせわあし", "bg": "bg_beginner_2.png"},
        {"word": "あきまつり", "ruby": ["あ", "き", "ま", "つ", "り"], "reverse": "りつまきあ", "bg": "bg_beginner_3.png"},
        {"word": "こんにちは", "ruby": ["こ", "ん", "に", "ち", "は"], "reverse": "はちにんこ", "bg": "bg_beginner_1.png"},
        {"word": "しんかんせん", "ruby": ["し", "ん", "か", "ん", "せ", "ん"], "reverse": "んせんかんし", "bg": "bg_beginner_2.png"},
        {"word": "あいうえお", "ruby": ["あ", "い", "う", "え", "お"], "reverse": "おえういあ", "bg": "bg_beginner_3.png"},
        {"word": "せんたくき", "ruby": ["せ", "ん", "た", "く", "き"], "reverse": "きくたんせ", "bg": "bg_beginner_1.png"},
        {"word": "れいぞうこ", "ruby": ["れ", "い", "ぞ", "う", "こ"], "reverse": "こうぞいれ", "bg": "bg_beginner_2.png"},
        {"word": "きょうりゅう", "ruby": ["きょ", "う", "りゅ", "う"], "reverse": "うりゅうきょ", "bg": "bg_beginner_3.png"},
        {"word": "ゆうえんち", "ruby": ["ゆ", "う", "え", "ん", "ち"], "reverse": "ちんえうゆ", "bg": "bg_beginner_1.png"},
        {"word": "がくせいたち", "ruby": ["が", "く", "せ", "い", "た", "ち"], "reverse": "ちたいせくが", "bg": "bg_beginner_2.png"},
        {"word": "きょうかしょ", "ruby": ["きょ", "う", "か", "しょ"], "reverse": "しょかうきょ", "bg": "bg_beginner_3.png"},
        {"word": "はくぶつかん", "ruby": ["は", "く", "ぶ", "つ", "か", "ん"], "reverse": "んかつぶくは", "bg": "bg_beginner_1.png"},
        {"word": "てんきよほう", "ruby": ["て", "ん", "き", "よ", "ほ", "う"], "reverse": "うほよきんて", "bg": "bg_beginner_2.png"},
        {"word": "じこしょうかい", "ruby": ["じ", "こ", "しょ", "う", "か", "い"], "reverse": "いかうしょこじ", "bg": "bg_beginner_3.png"},
        {"word": "でんしじしょ", "ruby": ["で", "ん", "し", "じ", "しょ"], "reverse": "しょじしんで", "bg": "bg_beginner_1.png"},
        {"word": "おもいでづくり", "ruby": ["お", "も", "い", "で", "づ", "く", "り"], "reverse": "りくづでいもお", "bg": "bg_beginner_2.png"},
        {"word": "たんじょうび", "ruby": ["た", "ん", "じょ", "う", "び"], "reverse": "びうじょんた", "bg": "bg_beginner_3.png"},
        {"word": "クリスマス", "ruby": ["く", "り", "す", "ま", "す"], "reverse": "すますりく", "bg": "bg_beginner_1.png"},
        {"word": "おしょうがつ", "ruby": ["お", "しょ", "う", "が", "つ"], "reverse": "つがうしょお", "bg": "bg_beginner_2.png"},
        {"word": "自動販売機", "ruby": ["じ", "ど", "う", "は", "ん", "ば", "い", "き"], "reverse": "きいばんはうどじ", "bg": "bg_beginner_3.png"},
        {"word": "公衆電話", "ruby": ["こ", "う", "しゅ", "う", "で", "ん", "わ"], "reverse": "わんでうしゅうこ", "bg": "bg_beginner_1.png"},
        {"word": "郵便番号", "ruby": ["ゆ", "う", "び", "ん", "ば", "ん", "ご", "う"], "reverse": "うごんばんびうゆ", "bg": "bg_beginner_2.png"},
        {"word": "電話番号", "ruby": ["で", "ん", "わ", "ば", "ん", "ご", "う"], "reverse": "うごんばわんで", "bg": "bg_beginner_3.png"},
        {"word": "住所録", "ruby": ["じゅ", "う", "しょ", "ろ", "く"], "reverse": "くろしょうじゅ", "bg": "bg_beginner_1.png"},
        {"word": "自己紹介", "ruby": ["じ", "こ", "しょ", "う", "か", "い"], "reverse": "いかうしょこじ", "bg": "bg_beginner_2.png"},
        {"word": "履歴書", "ruby": ["り", "れ", "き", "しょ"], "reverse": "しょきれり", "bg": "bg_beginner_3.png"},
        {"word": "免許証", "ruby": ["め", "ん", "きょ", "しょ", "う"], "reverse": "うしょきょんめ", "bg": "bg_beginner_1.png"},
        {"word": "保険証", "ruby": ["ほ", "け", "ん", "しょ", "う"], "reverse": "うしょんけほ", "bg": "bg_beginner_2.png"},
        {"word": "健康診断", "ruby": ["け", "ん", "こ", "う", "し", "ん", "だ", "ん"], "reverse": "んだんしうこんけ", "bg": "bg_beginner_3.png"},
        {"word": "予防接種", "ruby": ["よ", "ぼ", "う", "せ", "っ", "しゅ"], "reverse": "しゅっせうぼよ", "bg": "bg_beginner_1.png"},
        {"word": "救急車", "ruby": ["きゅ", "う", "きゅ", "う", "しゃ"], "reverse": "しゃうきゅうきゅ", "bg": "bg_beginner_2.png"},
        {"word": "消防車", "ruby": ["しょ", "う", "ぼ", "う", "しゃ"], "reverse": "しゃうぼうしょ", "bg": "bg_beginner_3.png"},
        {"word": "交通安全", "ruby": ["こ", "う", "つ", "う", "あ", "ん", "ぜ", "ん"], "reverse": "んぜんあうつうこ", "bg": "bg_beginner_1.png"},
        {"word": "防犯対策", "ruby": ["ぼ", "う", "は", "ん", "た", "い", "さ", "く"], "reverse": "くさいたんはうぼ", "bg": "bg_beginner_2.png"},
        {"word": "災害対策", "ruby": ["さ", "い", "が", "い", "た", "い", "さ", "く"], "reverse": "くさいたいがいさ", "bg": "bg_beginner_3.png"},
        {"word": "避難訓練", "ruby": ["ひ", "な", "ん", "く", "ん", "れ", "ん"], "reverse": "んれんくんなひ", "bg": "bg_beginner_1.png"},
        {"word": "非常口", "ruby": ["ひ", "じょ", "う", "ぐ", "ち"], "reverse": "ちぐうじょひ", "bg": "bg_beginner_2.png"},
        {"word": "環境問題", "ruby": ["か", "ん", "きょ", "う", "も", "ん", "だ", "い"], "reverse": "いだんもうきょんか", "bg": "bg_beginner_3.png"},
        {"word": "地球温暖化", "ruby": ["ち", "きゅ", "う", "お", "ん", "だ", "ん", "か"], "reverse": "かんだんおうきゅち", "bg": "bg_beginner_1.png"},
        {"word": "太陽光発電", "ruby": ["た", "い", "よ", "う", "こ", "う", "は", "つ", "で", "ん"], "reverse": "んでつはうこうよいた", "bg": "bg_beginner_2.png"},
        {"word": "風力発電", "ruby": ["ふ", "う", "りょ", "く", "は", "つ", "で", "ん"], "reverse": "んでつはくりょうふ", "bg": "bg_beginner_3.png"},
        {"word": "リサイクル", "ruby": ["り", "さ", "い", "く", "る"], "reverse": "るくいさり", "bg": "bg_beginner_1.png"},
        {"word": "ボランティア", "ruby": ["ぼ", "ら", "ん", "てぃ", "あ"], "reverse": "あてぃんらぼ", "bg": "bg_beginner_2.png"},
        {"word": "ディスカッション", "ruby": ["でぃ", "す", "か", "っ", "しょ", "ん"], "reverse": "んしょっかすでぃ", "bg": "bg_beginner_3.png"},
        {"word": "プログラミング", "ruby": ["ぷ", "ろ", "ぐ", "ら", "み", "ん", "ぐ"], "reverse": "ぐんみらぐろぷ", "bg": "bg_beginner_1.png"},
        {"word": "人工知能", "ruby": ["じ", "ん", "こ", "う", "ち", "の", "う"], "reverse": "うのちうこんじ", "bg": "bg_beginner_2.png"},
        {"word": "仮想現実", "ruby": ["か", "そ", "う", "げ", "ん", "じ", "つ"], "reverse": "つじんげうそか", "bg": "bg_beginner_3.png"},
        {"word": "キャッシュレス", "ruby": ["か", "っ", "しゅ", "れ", "す"], "reverse": "すれしゅっか", "bg": "bg_beginner_1.png"},
        {"word": "デジタルトランス", "ruby": ["で", "じ", "た", "る", "と", "ら", "ん", "す"], "reverse": "すんらとるたじで", "bg": "bg_beginner_2.png"},
        {"word": "温故知新", "ruby": ["お", "ん", "こ", "ち", "し", "ん"], "reverse": "んしちこんお", "bg": "bg_beginner_3.png"},
        {"word": "一石二鳥", "ruby": ["い", "っ", "せ", "き", "に", "ちょ", "う"], "reverse": "うちょにきせっい", "bg": "bg_beginner_1.png"},
        {"word": "弱肉強食", "ruby": ["じゃ", "く", "に", "く", "きょ", "う", "しょ", "く"], "reverse": "くしょうきょくにくじゃ", "bg": "bg_beginner_2.png"},
        {"word": "喜怒哀楽", "ruby": ["き", "ど", "あ", "い", "ら", "く"], "reverse": "くらいあどき", "bg": "bg_beginner_3.png"},
        {"word": "森羅万象", "ruby": ["し", "ん", "ら", "ば", "ん", "しょ", "う"], "reverse": "うしょんばらんし", "bg": "bg_beginner_1.png"},
        {"word": "以心伝心", "ruby": ["い", "し", "ん", "で", "ん", "し", "ん"], "reverse": "んしんでんしい", "bg": "bg_beginner_2.png"},
        {"word": "七転八起", "ruby": ["し", "ち", "て", "ん", "は", "っ", "き"], "reverse": "きっはんてちし", "bg": "bg_beginner_3.png"},
        {"word": "三日坊主", "ruby": ["み", "っ", "か", "ぼ", "う", "ず"], "reverse": "ずうぼかっみ", "bg": "bg_beginner_1.png"},
        {"word": "十人十色", "ruby": ["じゅ", "う", "に", "ん", "と", "い", "ろ"], "reverse": "ろいとんにうじゅ", "bg": "bg_beginner_2.png"},
        {"word": "一生懸命", "ruby": ["い", "っ", "しょ", "う", "け", "ん", "め", "い"], "reverse": "いめんけうしょっい", "bg": "bg_beginner_3.png"},
        {"word": "自由研究", "ruby": ["じ", "ゆ", "う", "け", "ん", "きゅ", "う"], "reverse": "うきゅんけうゆじ", "bg": "bg_beginner_1.png"},
        {"word": "読書感想文", "ruby": ["ど", "く", "しょ", "か", "ん", "そ", "う", "ぶ", "ん"], "reverse": "んぶうそんかしょくど", "bg": "bg_beginner_2.png"},
        {"word": "計算ドリル", "ruby": ["け", "い", "さ", "ん", "ど", "り", "る"], "reverse": "るりどんさいけ", "bg": "bg_beginner_3.png"},
        {"word": "漢字練習", "ruby": ["か", "ん", "じ", "れ", "ん", "しゅ", "う"], "reverse": "うしゅんれじんか", "bg": "bg_beginner_1.png"},
        {"word": "理科の実験", "ruby": ["り", "か", "の", "じ", "っ", "け", "ん"], "reverse": "んけっじのかり", "bg": "bg_beginner_2.png"},
        {"word": "修学旅行", "ruby": ["しゅ", "う", "が", "く", "りょ", "こ", "う"], "reverse": "うこりょくがうしゅ", "bg": "bg_beginner_3.png"},
        {"word": "文化祭", "ruby": ["ぶ", "ん", "か", "さ", "い"], "reverse": "いさかんぶ", "bg": "bg_beginner_1.png"},
        {"word": "卒業式", "ruby": ["そ", "つ", "ぎょ", "う", "し", "き"], "reverse": "きしうぎょつそ", "bg": "bg_beginner_2.png"},
        {"word": "入学式", "ruby": ["にゅ", "う", "が", "く", "し", "き"], "reverse": "きしくがうにゅ", "bg": "bg_beginner_3.png"},
        {"word": "運動会", "ruby": ["う", "ん", "ど", "う", "か", "い"], "reverse": "いかうどんう", "bg": "bg_beginner_1.png"},
        {"word": "遠足", "ruby": ["え", "ん", "そ", "く"], "reverse": "くそんえ", "bg": "bg_beginner_2.png"},
        {"word": "お遊戯会", "ruby": ["お", "ゆ", "う", "ぎ", "か", "い"], "reverse": "いかぎうゆお", "bg": "bg_beginner_3.png"},
        {"word": "参観日", "ruby": ["さ", "ん", "か", "ん", "び"], "reverse": "びんかんさ", "bg": "bg_beginner_1.png"},
        {"word": "都道府県", "ruby": ["と", "ど", "う", "ふ", "け", "ん"], "reverse": "んけふうどと", "bg": "bg_beginner_2.png"},
        {"word": "市町村", "ruby": ["し", "ちょ", "う", "そ", "ん"], "reverse": "んそうちょし", "bg": "bg_beginner_3.png"},
        {"word": "国立公園", "ruby": ["こ", "く", "り", "つ", "こ", "う", "え", "ん"], "reverse": "んえうこつりくこ", "bg": "bg_beginner_1.png"},
        {"word": "観光名所", "ruby": ["か", "ん", "こ", "う", "め", "い", "しょ"], "reverse": "しょいめうこんか", "bg": "bg_beginner_2.png"},
        {"word": "春夏秋冬", "ruby": ["しゅ", "ん", "か", "しゅ", "う", "と", "う"], "reverse": "うとうしゅかんしゅ", "bg": "bg_beginner_3.png"},
        {"word": "二十四節気", "ruby": ["に", "じゅ", "う", "し", "せ", "っ", "き"], "reverse": "きっせしうじゅに", "bg": "bg_beginner_1.png"},
        {"word": "年中行事", "ruby": ["ね", "ん", "ちゅ", "う", "ぎょ", "う", "じ"], "reverse": "じうぎょうちゅんね", "bg": "bg_beginner_2.png"},
        {"word": "伝統工芸", "ruby": ["で", "ん", "と", "う", "こ", "う", "げ", "い"], "reverse": "いげうこうとんで", "bg": "bg_beginner_3.png"},
        {"word": "日本文化", "ruby": ["に", "ほ", "ん", "ぶ", "ん", "か"], "reverse": "かんぶんほに", "bg": "bg_beginner_1.png"},
        {"word": "音楽鑑賞", "ruby": ["お", "ん", "が", "く", "か", "ん", "しょ", "う"], "reverse": "うしょんかくがんお", "bg": "bg_beginner_2.png"},
        {"word": "読書習慣", "ruby": ["ど", "く", "しょ", "しゅ", "う", "か", "ん"], "reverse": "んかうしゅしょくど", "bg": "bg_beginner_3.png"},
        {"word": "料理教室", "ruby": ["りょ", "う", "り", "きょ", "う", "し", "つ"], "reverse": "つしうきょりうりょ", "bg": "bg_beginner_1.png"},
    ],
};

const SAMPLE_WORDS = {
    beginner: QUESTION_DATABASE.beginner.map(q => q.word),
    intermediate: QUESTION_DATABASE.intermediate.map(q => q.word),
    advanced: QUESTION_DATABASE.advanced.map(q => q.word)
};
